### ISSUE TITLE
Test porting over an Ethereum dapp to Celo

### ISSUE THREAD

**Issue by arthurgousset** [celo-org/celo-monorepo#10060]

**Comment by Jesse-Sawa** [comment]
Test: Uniswap v3 deployment
Source: Uniswap 
Tools: ethers
Environment: Celo Mainnet

Original deployment of Uniswap V3 contracts in May of 2022  required a modification to the js build output in order to circumvent the ethersjs incompatibility due to missing required block headers. 

Although since [1.7.0-stable](https://github.com/celo-org/celo-blockchain/releases/tag/v1.7.0) made it to production, the same deploy script works seamlessly; contracts were deployed in this test with the unmodified script.

**Comment by arthurgousset** [comment]
Amazing news @Jesse-Sawa. Thanks for testing this!!!

**Comment by arthurgousset** [comment]
Closing this issue after @Jesse-Sawa's test
