### ISSUE TITLE
Cli can't upvote proposals in upvote stage when other proposals are ready for dequeuing

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#10064]
### Expected Behavior

Any proposal in the upvote stage can be upvoted. Proposals ready for dequeuing should be dequeued when attempting to upvote.

### Current Behavior

Assuming these are the the proposals in upvote stage:
(id, upvotes)
#1 0
#2 1
#3 1
#4 1

If the cli tries to upvote #1 it will fail with 
```
Running Checks:
   ✔  0x... is vote signer or registered account
   ✔  1 is an existing proposal
   ✔  1 is in stage Queued
Sending Transaction: upvoteTx... failed: Error: execution reverted: invalid lesser key
    Error: Error: execution reverted: invalid lesser key
```

If it tries to upvote #2, #3 or #4, it will get:

```
Retrieving derivation Paths [ 0 ]
Running Checks:
   ✔  0x... is vote signer or registered account
   ✔  2 is an existing proposal
   ✔  2 is in stage Queued
Sending Transaction: upvoteTx... failed: Error: execution reverted: cannot upvote a proposal not in the queue
    Error: Error: execution reverted: cannot upvote a proposal not in the queue
```

**Comment by montera82** [comment]
Picked this up again, and i need more clarity on how to replicate the behavior to help me determine the better solution

## Update
Spent some time investigating this, and could not replicate it, it seems this problem is solved. 
@martinvol  is this ticket still valid?
https://www.loom.com/share/b7fa8f837864470b9267eeaa59562e37?sid=484fcbc8-26ce-48f1-82b6-ad81e32797bb
