### ISSUE TITLE
Verify Core contracts on CeloScan

### ISSUE THREAD

**Issue by pahor167** [celo-org/celo-monorepo#10365]

**Comment by arthurgousset** [comment]
Re-opening this issue because the core contracts are not verified on celoscan.xyz (for example 
[OdisPayments.sol](https://celoscan.io/address/0x9ea5e9b9b48a72325d59b3eba147f42b1b14bf78)). 

The list of core contract addresses (implementation and proxy contracts) can be found here: https://dhutch-test.celo-networks-dev.org/mainnet

**Comment by arthurgousset** [comment]
Closing this issue because it turns out that OdisPayment was the only contract that wasn't verified. It wasn't verified because the team used the following [documentation](https://docs.celo.org/contract-addresses) during the process which doesn’t mention OdisPayments and has out-of-date implementation contract addresses. 
All other core contracts are verified ✅
