### ISSUE TITLE
Blockscout SNBAT to OOM our transaction nodes

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#1045]
### Expected Behavior

We should figure out how to enable the indexer without OOMing

### Current Behavior

Enabling the blockscout indexer on alfajores causes the tx nodes to OOM

**Comment by jcortejoso** [comment]
After some digging with @tkporter, we have been thinking about the root cause of the issue. The problem reproduces in new nodes with a updated version (from upstream) of blockscout.
We have open an issue on poanetwork/blockscout after talking with them on gitter: https://github.com/poanetwork/blockscout/issues/2729

**Comment by nambrot** [comment]
I believe @tkporter fixed this
