### ISSUE TITLE
Devs SBAT remove redux-thunk from mobile

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#111]
### Expected Behavior

We no longer have redux-thunk

### Current Behavior

Still have some thunk actions

**Comment by jeanregisser** [comment]
I've started working on this.

Removing redux-thunk and moving remaining thunk actions to redux-saga means we'll have to go through the redux store for keeping some things that were stored until now in local component state.

For instance, for the following async action that currently uses redux-thunk:

https://github.com/celo-org/celo-monorepo-old/blob/3b526f0408d610c21985337b3b98a107e4947345/packages/mobile/src/pincode/SystemAuth.tsx#L47-L52

We'll have to store `isSettingPin` in the redux store.

I'm totally fine with this, I just want to be sure it's what we want since it makes handling simple async actions like this one a bit more complex.

**Comment by jeanregisser** [comment]
@jmrossy for this particular case, yes it looks like we could do what you said.

But in general, to transition code awaiting on a promise returned by redux-thunk to redux-saga means the state has to move to the redux store to know when the async action starts and stops.

Here's another instance which requires the `inviteInProgress` state to go in the redux store:

https://github.com/celo-org/celo-monorepo-old/blob/0df549bcf4e147b2ac593aa7a19260ba17a77ff5/packages/mobile/src/account/InviteReview.tsx#L127-L131

**Comment by jeanregisser** [comment]
People have struggled with this particular case of saga <-> component communication:
https://github.com/redux-saga/redux-saga/issues/907

I have read all comments on that thread and saw the solutions people have tried over the years.
One that looked interesting was https://github.com/diegohaz/redux-saga-thunk

But overall I feel if we're going full saga, we should embrace the [redux way of doing this](https://redux.js.org/advanced/async-actions) and use appropriate actions (START, SUCCESS, FAILURE) and redux state to handle this. 
I know it means a bit more ceremony around async actions but at least it's normal redux flow.

Would love your thoughts on this @cmcewen @jmrossy.

**Comment by jeanregisser** [comment]
Another interesting case for moving away from redux-thunk is the `updateSuggestedFee` action:

https://github.com/celo-org/celo-monorepo/blob/91cc59fe6a2fcaba93d64da76f3846c9cdd61141/packages/mobile/src/send/actions.ts#L102-L137

This currently updates a global `suggestedFee` state but it looks like it should be component specific.
