### ISSUE TITLE
Validators SBAT have synthetic verification load

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#1222]
- [ ] Extend the tracer tool to be able to receive SMS via Twilio
- [ ] Generate verification requests for those numbers 
- [ ] Track overall number of SMS received
- [ ] Figure out *which* validators should have sent texts and track per-validator receive rates

**Comment by timmoreton** [comment]
Probably depends on #982

**Comment by nambrot** [comment]
So starting to think about this (for the stakeoff)

Ideally, we have a public way of determining the statistics in something like Blockscout. https://github.com/celo-org/celo-monorepo/issues/1702 tracks that. It would be nice because
1) People have to trust us less
2) We'll have to build something eventually for Mainnet

However, since we'll only count CLabs-requested attestations (otherwise one could game the game), we could also just keep track of it as CLabs.

I don't think there is much synergy with our existing tracer tool/load-test besides the fact that it would be beneficial to be able to run this regularly. We probably don't want to load-test this, as it can cost quite a good amount of money to do so, but doing a few a day to ensure the network being up might be a good idea.

Otherwise, this is probably easiest to build into celotool as a command, very similarly to the 

- `celotool account verify-automatic`
- grabs the mnemonic from the ENV, generates the relevant private key
- uses one of the existing numbers (or maybe just request a random new one from twilio)?
- requests an additional attestation
- polls twilio for incoming text messages (since we can't easily/dont want to register a webhook)
- complete the attestation

For operational purposes, we'll want to use our existing logging/alerting mechanism to
1) let us know when verification seems to be broken
2) maybe even let the validator know

**Comment by nambrot** [comment]
Plan:
- use mostly the design of the load-test #1806 
- amend it by reading some configuration from an in memory store to allow for graceful termination.
- adds json structured logging
