### ISSUE TITLE
Local currency rounding can show discrepancies between amount input and confirmation screen for Euro

### ISSUE THREAD

**Issue by jeanregisser** [celo-org/celo-monorepo#1305]
### Expected Behavior

When sending an amount using a local currency, the amount entered and the amount in the confirmation screen should be the same.

### Current Behavior

When sending an amount using a local currency, the amount entered and the amount in the confirmation screen can be slightly different.

Looks like the logic in place is not enough: 
https://github.com/celo-org/celo-monorepo/blob/3e4b1866c0917b417a2696ea8a95b9f88db4ce3d/packages/mobile/src/localCurrency/convert.test.ts#L9-L25

**Input screen**
![image](https://user-images.githubusercontent.com/57791/66640858-faf1d100-ec19-11e9-8294-330f0f1fe6ab.png)

**Confirmation screen**
![image](https://user-images.githubusercontent.com/57791/66640902-0d6c0a80-ec1a-11e9-8cfc-42eb934787ea.png)

**Comment by jeanregisser** [comment]
The raw exchange rate showing this prob is `0.9066183137`

**Comment by Lss-Ankit** [comment]
@jmrossy I have also observed the same issue and observed that the issue is repro only for EUR currency. I have verified with the remaining (CAD, MXN, PHP, USD ) currency and observe that the issue does not repro. 
Attachment: [Android_CurrencyIssue.mp4](https://drive.google.com/file/d/1KqOAxBuQQiaGFTsmZm2YHXb9PtXhddNH/view?usp=sharing)
