### ISSUE TITLE
Prompt for pin on app open every time

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#1328]
### Expected Behavior

each time the celo wallet is opened, the pin should be requested

### Current Behavior

if a phone is stolen while unlocked, a user's celo wallet can be accessed

**Comment by Lss-Ankit** [comment]
@annakaz I have observed that security PIN prompt is not shown every time while the user turning ON/OFF "Celo Lite" toggle from the "Setting" . 

Attachment: [Android_CeloLite_SecurityPIN.mp4](https://drive.google.com/file/d/1BFt-ZIBw6W3kTYOYyrACyURzrad8cFLH/view?usp=sharing)

**Comment by Lss-Ankit** [comment]
Verified with Android Celo Alfa RC build : 1.6.2 (101648776) & (104794504) and found that issue is reproduce while proceeding for payment when Data saver toggle is 'On/Off' 

Verified on Device: Samsung Galaxy A8 Pro (8.1.0), Google Pixel XL 2 (9.0)

Attachment : [Android_Authentication pin is not shown](https://drive.google.com/file/d/1kg9hW7piiekWhwTYWh3krKzs5WA4Ki1X/view?usp=sharing)

**Comment by i1skn** [comment]
@jmrossy @nityas I have a question regarding this one, cause I do not see a bug here. When we are toggling Data Saver - we need a PIN, so we ask a user for it and **cache it**. So, when we do a transaction - we take it from the cache. Is not that how it should be working? Thanks!

**Comment by nityas** [comment]
Yes! That is expected behavior- how long is the PIN cached for?

**Comment by i1skn** [comment]
@nityas Currently for 5 minutes:
https://github.com/celo-org/celo-monorepo/blob/09aa79baf65b8e26967bc28127bf1f9cb646f2fc/packages/mobile/src/pincode/PincodeCache.ts#L1

**Comment by nityas** [comment]
that's perfect then! My guess is this issue predates the PIN improvements, so seems we can close this issue out, thanks Ivan :)
