### ISSUE TITLE
[Android] Onboarding Verification fails

### ISSUE THREAD

**Issue by wpank** [celo-org/celo-monorepo#1330]
### Expected Behavior

Please describe the behavior you are expecting

Onboarding should proceed successfully. 

### Current Behavior

What is the current behavior?

The onboarding process fails upon trying to verify the phone number. 

It will hang on the following screen:

![20191014_140635](https://user-images.githubusercontent.com/9498646/66783799-8f179e80-ee8d-11e9-8777-f17737bad576.jpg)

And then eventually timeout:

![20191014_141544](https://user-images.githubusercontent.com/9498646/66783842-a6568c00-ee8d-11e9-92ba-2306b8cba598.jpg)

Closing/restarting the app and restarting the phone will yield the same result. 

This is on a Samsung Galaxy Note 8 with Android 9 Pie

**Comment by Lss-Ankit** [comment]
@annakaz Verified with play store build v1.5.0 and new build zero-sync build v1.5.0 and observed that three verification code is not received when a new user signs up, hence we are blocked to sign up with new user. 
**Investigation** I have tried to sign up with back up key and able to sign up. 
[Attachment. ](https://drive.google.com/file/d/1vOzMgt2ZL26JYFDqcL2Bhp1AOiV8uXsp/view?usp=sharing)

**Comment by nityas** [comment]
Thanks for reporting! @wpank could you please move this issue report to the Celo Forum at https://forum.celo.org/? There appear to be some network issues at the moment, and we'll be able to help troubleshoot there.

**Comment by cmcewen** [comment]
@wpank thanks for reporting this, and sorry to take so long to get back to you. The issue here is that our Attestations contract was hitting the block gas limit when requesting text messages - getting the current set of validators takes a lot of gas. We merged and deployed a fix to use a precompiled contract (https://github.com/celo-org/celo-blockchain/pull/441), and also updated the app, so it should be working now. You'll have to get a new invite, but otherwise should be all good to go
