### ISSUE TITLE
[iOS] OnBoarding Phone Number Verification Fails

### ISSUE THREAD

**Issue by Kai-Bailey** [celo-org/celo-monorepo#1568]
### Expected Behavior

I would receive three text messages and my phone number would be verified.

### Current Behavior

I only received two text messages. I retried the verification multiple times but the third text is never sent.

### Other Details
Country: Canada
Phone: iPhone 7
iOS: 13.1.3
Related Issue: #1330 

![IMG_4567](https://user-images.githubusercontent.com/24615518/68074169-ce832d80-fd5d-11e9-8291-c58c7fa05773.png)

**Comment by nityas** [comment]
Thank you for filing this issue- there have been some issues on the alfajores test network with validator messages not always being sent (see https://forum.celo.org/c/alfajores-testnet for some discussion on this). Some changes have been made recently and the network has since been reset, we recommend trying again now with the latest application (you'll need a new invite code)

**Comment by Kai-Bailey** [comment]
I re-downloaded Celo Wallet and got a new invite code. The verification process worked great! This is a super cool project. Can't wait for the Mainnet launch!

**Comment by nityas** [comment]
Great to hear it worked out better this time- thank you for the patience! I'll close this specific issue out now, we always welcome any feedback :)
