### ISSUE TITLE
[32-bit device specific] Error “Redeem invite time out” is shown on “Enter invite code” after pasting the invitation code. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#1668]
**Frequency:** 100%
**App version:** Pilot build v1.5.1
**Used APK: ** app-x86-pilot.apk
**Repro on:** Samsung Galaxy A5 (7.0), Moto z play (7.0)
**Does not repro: ** Google Pixel XL (8.1), Google Pixel XL 2 (9.0)

**Repro Steps:** 
1) Launch the app. 
2) Enter name, Country and phone number. 
3) Tap on the Continue button. 
4) Paste the invitation code 
5) Wait for the moment and observed. 
**Impact:** User is blocked to sign up in-app. 
**Investigation:** Issue does not repro for 64-bit devices. 
**Current Behavior:**  Error “Redeem invite time out” is shown 
**Expected Behavior:** User should be able to accept invite code successfully and proceed for sign up. 
**Attachment:**[ Android_32-bit_InvitationIssue.mp4](https://drive.google.com/file/d/1xOxQuvIGfTw4ZChYZ-h8tjVvq6nKuZ23/view?usp=sharing) (Bug observe at  1:17 sec)

**Comment by i1skn** [comment]
After some experiments we've figured that this bug disappears if we update web3 version to `1.2.4`. But because of `1.2.2` introduces braking changes - it is not a trivial update. Also, @cmcewen discovered, that this bug reproducible only in Hermes.

Here is the branch with my attempt to update `web3` version - https://github.com/celo-org/celo-monorepo/tree/i1skn/migrate-to-web3-1.2.4

**Comment by ValoraQA** [comment]
Hi @i1skn we have verified this issue on latest Android build V1.15.1 & Testflight build V1.15.1(64) and found as per the design change issues got fixed .
Thanks

**Comment by i1skn** [comment]
@Celoqa I've left Clabs, so it's better to tag someone else here 🙂
