### ISSUE TITLE
[Wallet] US phone number users SBAT have number recognized as US, not Canada

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#1701]
### Expected Behavior

Users with US phone numbers who select their phone number when prompted on the Welcome screen should have "United States" selected as the corresponding country. 

Not sure how hard it will be to differentiate between US and Canada phone numbers (which both start with +1) but a quick fix would be to default to US instead of to Canada, as we currently have more users in the US than in Canada. 

### Current Behavior

Users with US phone numbers who select their phone number when prompted on the Welcome screen have "Canada" selected as the corresponding country, as Canada and US share the country code +1.

![Screenshot_20191113-143011](https://user-images.githubusercontent.com/16907027/68810285-a54a8300-0622-11ea-8a9e-2691b1022aa2.png)

**Comment by martinvol** [comment]
The underlying problem is that in order to get the country out of a number, we would need `PhoneNumberOfflineGeocoder ` which is not included in the javascript `libphonenumber` implementation: https://www.npmjs.com/package/google-libphonenumber#unavailable-methods-and-classes

To work this around, we could:
1. Research another tool and add that our parsing toolkit.
2. Avoid autocompleting they country field for countries that share country code (I only know of the US and Canada).

**Comment by jmrossy** [comment]
@martinvol #1 could be a nice long term solution but short term I think we can just have preset defaults for the known cases where phone country codes are ambiguous, such as defaulting to the US for +1

**Comment by martinvol** [comment]
Thanks to @jeanregisser I figured out a way to recognize US vs Canada, should be working fine now.
