### ISSUE TITLE
Proxy IP should be fetched without needing to run the container in quickstart guide

### ISSUE THREAD

**Issue by asaj** [celo-org/celo-monorepo#1877]
### Expected Behavior

Currently, we fetch the proxy IP address by running a command in a running container. However, to run that container, we need to know the proxy IP address (see #1876). We should fetch the IP address in a different way to avoid the circular dependency

### Current Behavior

Circular dependency

**Comment by jcortejoso** [comment]
Hi @asaj. 
we supposed that with `--proxy.internalendpoint :30503` we are listening in all the available interfaces. Because is a docker container, it will only have two interfaces (localhost and the one assigned dynamically by docker), so the result will be the same as setting the assigned ip. 
If we want to limit the listening interfaces we can control it with the `publish,-p` option of docker (` -p localhost:8545:8545 -p 8546:8546 -p 30303:30303 -p 30303:30303/udp -p 30503:30503 -p 30503:30503/udp`).

We can try also setting `0.0.0.0` but I guess the result would be the same. Same configuration is applied for terraform(https://github.com/celo-org/celo-monorepo/blob/trevor/baklavastaging-nov-21/packages/terraform-modules/testnet/modules/full-node/startup.sh#L54) and k8s.

**Comment by kevjue** [comment]
> Hi @asaj.
> we supposed that with `--proxy.internalendpoint :30503` we are listening in all the available interfaces. Because is a docker container, it will only have two interfaces (localhost and the one assigned dynamically by docker), so the result will be the same as setting the assigned ip.
> If we want to limit the listening interfaces we can control it with the `publish,-p` option of docker (` -p localhost:8545:8545 -p 8546:8546 -p 30303:30303 -p 30303:30303/udp -p 30503:30503 -p 30503:30503/udp`).
> 
> We can try also setting `0.0.0.0` but I guess the result would be the same. Same configuration is applied for terraform(https://github.com/celo-org/celo-monorepo/blob/trevor/baklavastaging-nov-21/packages/terraform-modules/testnet/modules/full-node/startup.sh#L54) and k8s.

Hey @jcortejoso - For proxy setup, the machine should have 2 different network interfaces, one connect to the internet (and will have a public ip address) and one connected to a private network (and it will have a private ip address).

The proxy will get new blocks, txns, and consensus messages, and then forward them off to the validator via the other network interface (which should be connected to a private network).

You mention that `--proxy.internalendpoint :30503` will listen to all interfaces, but that would open up a security risk, as that endpoint should ONLY be listening to the internal interface.
