### ISSUE TITLE
Add Open Graph data and images

### ISSUE THREAD

**Issue by aaronmgdr** [celo-org/celo-monorepo#2169]
Brandkit pages should use <OpenGraph /> component so they have nice previews on facebook and twitter and such.

will need Images 1500x1500 for the preview. 

decision: 1 preview per page or can we share between pages in brand kit?

Also missing images for 

/build/wallet
/build/faucet
and pages like terms and stake off terms / privacy

**Comment by hanchia920** [comment]
Hey team, attached are the needed assets for wallet, faucet, and brandkit. All of these assets are 1500x1500 (1:1). Since all content is vertically centered within the frame, they can easily be cropped down to 1.91:1 or 2:1 for various social media platforms.

**- /build/wallet**
Created from elements in the hero section of /build/wallet.

**- /build/faucet**
Created using an abstract graphic from the homepage. The idea here is to represent "additional funds available upon request".

**- brandkit**
The colorful Coins represent aspects of the Celo brand, while the box and dotted line represent the more technical content of the brand guideline.

Let me know what you think! Open to more exploration if you think these don't fly.

[ogimages-191212.zip](https://github.com/celo-org/celo-monorepo/files/3957764/ogimages-191212.zip)
