### ISSUE TITLE
Audit auth rules for faucet db

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#229]
Can unauthenticated users write to the faucet DB and read any value?
They should not have write perms and should only be able to read / subscribe to requests related to them

**Comment by mcortesi** [comment]
Pretty sure we need to restrict anonymous `push` on the request list.
It was enabled at first, since that's how the browser enqueued request, but later we moved that logic to the web server, so to verify the captcha and then enqueue.

And also, we have to use an authenticated user/admin for the webserver now

**Comment by ashishb** [comment]
I redeployed the new faucet and new dev.celo.org. Everything works. @cmcewen has redeployed the new production website and that works as well.
