### ISSUE TITLE
Testent monitoring should verify a monotonically increasing stream of blocks

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2633]
During a recent incident the block numbers coming from our monitored nodes went from ~380,000 back to 1, and was reset to 1 repeatedly. This should be a alertable event.

**Comment by nategraf** [comment]
@tkporter do you have any intuition for how easy/hard this will be to do? If easy I think it'd be worth doing now, and I'd like to do it to learn how these things are done.

**Comment by tkporter** [comment]
The way we currently have our alerts set up is by looking at `RECEIVED_BLOCK` logs from transaction-metrics-exporter. It looks like that log is given even when syncing, which you can see if you look at the graph of the `received-blocks-low-baklava` alert for the past week:

<img width="522" alt="Screen Shot 2020-02-06 at 12 10 56 PM" src="https://user-images.githubusercontent.com/20362969/73974749-c517dd00-48d9-11ea-855f-017d7dd96270.png">

 We could create a new log, something like `NEW_BLOCK`?

I think the 2 easiest ways would be to either:
1. Make TME stateful to keep track of the highest block # it's seen
2. Look at the timestamp of the block and make sure it's recent

The first one is dangerous because TME might restart, in which case we'll get false positives for old blocks if the node TME is aware of is syncing, so maybe the second is the best approach

TME uses our internal node so it should be relatively safe for ensuring the network is still producing blocks. I think we should definitely figure out a way to monitor each individual node we have that is publicly accessible (accessible by the network & RPCs), which I don't have a strong intuition yet of how we would do because a new TME for each node is unrealistic
