### ISSUE TITLE
Benchmark Forno

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#2681]
We need to understand what is FORNO capable of, and what changes we need to make in order to have a version open to the public.

**Please, add here other things to check**

**Feature Wise**
1. The json RPC has the concept of subscriptions (`eth_newfilter`) which are stateful. So Forno should have sticky session when load balancing. A test for this setup would be interesting.
2. Do we support websocket connections?

**Load testing / DoS protection**

1. `eth_call` allows users to make call for old blocks. The older the block the harder geth need to work to return an answer. We should analyze the limits, and see if there's a why to limit historical queries.
2. `eth_estimateGas/eth_call`. By calling estimateGas on complex call, or very long ones, we can DoS geth. The node actually has a cmd line flag to limit this. (`--rpc.gascap value`). We should set, and check this with a test.

**Other checks**

1. nodes behind the load balancer should not be publicly accessible.
2. nodes should not have accounts exposed (`eth_accounts`)
3. nodes should all have the same `etherbase` which should be used as the gatewayFeeRecipient.

**Comment by annakaz** [comment]
+1 to the importance of sticky sessions, this is also helpful if one of the nodes isn't synced. In the past we had a tx node that wasn't synced and were seeing balances vary in repeated balanceOf calls

> Do we support websocket connections?

In the past, we chose to use an HTTPS connection with the wallet because we did not want to send plain-text data with a web socket connection and geth doesn't support wss ([explanation here](https://github.com/celo-org/celo-monorepo/tree/master/packages/mobile#why-https-provider)). But we can revisit this

**Comment by yorhodes** [comment]
To prepare for the February launch of the SDK and the Nigeria trip, load testing of Forno was prioritized for a smooth first development experience with Celo. Because of the lack of economic value tied up in the test networks, extensively malicious DoS vectors were possible but unlikely. 

For the upcoming large-scale product partnerships, the recommendation is to move towards a third party solution who has made it their business to host, maintain, and optimize[ Infura-like setups ](https://blog.infura.io/building-better-ethereum-infrastructure-48e76c94724b/) while Forno continues to be used as a small-scale developer sandbox. These businesses have done the hard work of determining how to classify and rate limit traffic differentiated on archive requirements, and mitigate DDoS threats. 

The `Election.electValidatorSigners()` endpoint was identified as the most expensive `eth_call` in the suite of Celo smart contracts (most gas intensive). To simulate worst-case load of the Semicolon conference, the CPU usage across the tx-nodes was manually monitored in stackdriver while processing several of these requests simultaneously. It was deemed that the current auto-scaling configuration would easily handle the anticipated traffic.

Following a [successful trial in Lagos](https://medium.com/celoorg/introducing-the-celo-sdk-e5377a67b6e6), some of this work was de-prioritized with the anticipation of a more robust solution in future and an understanding of the minimal current requirements (milestone 1 timeline).
