### ISSUE TITLE
Define and apply versioning schema for our public packages (utils, contractKit, dappKit)

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#2683]
We need a npm package versioning scheme that address:

 1. depend on published vs unpublished version (yarn workspace)
 2. version scheme that allow new versions for different environment
 3. version scheme that is lineal

With this, we also need to create publishing script to make the process of publishing packages painless.

**Comment by mcortesi** [comment]
Some considerations:

 * On monorepo there are packages that depend on other packages
 * Deployment for packages is an important consideration: 
      * Some packages are deployed in GoogleAppEngine or Firebase functions, which mean they won't have the full monorepo on build time
      * Some packages are deployed as npm packages
      * Some packages are deployed as docker images
 * When a package doesn't build with full monorepo for deployment, this means it MUST depend on published version of other packages.

**Comment by mcortesi** [comment]
There's a scenario to consider...

If you depend on version x.y.z of packageA. And packageA package.json on your branch has that same version (x.y.z). But there's also a published version on npm for x.y.z (a few months old). 

Then it will depends on how you build your package; if you have the whole monorepo and run `yarn build` you will depend on your branch version. But if you are in a docker context, or publishing in GAE or Firebase Function, you won't have the full monorepo, so you will end up depending on the npm version.

Both version are probably different, so you won't have reproducible build, or stable builds.

That's why one of the recommendations is that package.json on your branch (or whatever branch) should always refere to an UNPUBLISHED version (not in npm). So that when you attempt to build in a place where you can't access the full monorepo, it will fail.

**Comment by mcortesi** [comment]
A simple solution to that is to use suffix or a keyword... so all package.json must have a version as `X.Y.Z-UNPUBLISHED` or maybe just a version named `UNPUBLISHED`

**Comment by mcortesi** [comment]
The second problem; is how to handle different environments. For example, integration, alfajores & baklava.

Example:

 - Jan 10 - publish alfajores (branch release/alfajores-10-1)
 - We make changes to contractKit on master
 - Feb 10 - publish baklava from master (branch release/baklava-10-2)
 - More changes on contractKit on master
 - Feb 15 Hot fix to contractKit on alfajores; done on branch `release/alfajores-10-1`. We need to publish a new contractKit which version number should we use???

**Comment by mcortesi** [comment]
A possible solution to that is:

 * Jan 10 - publish contractKit version 1.1.0 for alfajores.... and Master package.json set to work on version 1.2.0
* Feb 10 - publish contractKit version 1.2.0 for baklava.... and Master package.json set to work on version 1.3.0
More changes on contractKit on master
* Feb 15 Hot fix, publish contractKit version `1.1.1`

So the idea... is with every deploy we need to leave "version space" for hotfixes... so on master we change the MINOR version.

**Comment by nategraf** [comment]
So after chatting with Mariano here are my thoughts on a versioning scheme:

Assumptions:
1. Each testnet has an associated release branch from which the testnet should be deployed and upgraded.
2. Work should almost always be completed on `master`, and release branches should acquire the changes by merging `master` into the release branch we possible, or a cherry-pick when that would result incompatible changes.

One problem we are trying to solve is to answer the question of which version of an NPM package a user should install to interact with a particular network. I propose we use NPM tags to solve that issue such that a user can always run `@celo/contractkit@alfajores` to get the latest version of `contractkit` compatible with Alfajores, and similar for other testnets. In our guides we should make sure we suggest they use the network tag whenever they are installing an NPM package to interact with a testnet.

Whenever possible the version pointed to by the network tag should be an older version of the mainline package (i.e. the one build from `master`). This will likely change when mainnet is released and the testnets will generally be in front of mainnet.

When a testnet must diverge from the mainline, such as if a network specific fix to a package is needed or if a special version must be created that includes a new feature with tweaks to make it compatible. The version number should be the version of the package the release is based on, with an `networkx` suffix. (e.g. if Alfajores is deployed at version `0.1.1` of `monorepo`, and later a spotfix, the the version should be `0.1.1-alfajores1` and if it happens again before the next upgrade it should become `0.1.1-alfajores2`) When a testnet is reset, it should be brought up to date with the latest mainline version.

On a slightly different note, the question arose of what to do when deploying a new version of a package like `celocli` which has `utils` and `contractkit` as dependencies. If changes have been made to `utils` or `contractkit` it is important to publish those packages as well. In order to know when changes have been made, and a new version of the package must be deployed, or the package is unchanged and no release is needed, each version should have its commit hash as a tag in NPM. This is the process I've been following in the [last couple of releases](https://www.npmjs.com/package/@celo/contractkit), and I believe its a decent way of recording the commit hash, although a better scheme may exist.

**Comment by yerdua** [comment]
Here's the process I'm working on implementing in a script to publish a package:

1. Confirm we're on latest master (or the latest for a network branch). We should only be publishing code that made it through code review and has been merged.
2. Determine if the package or any of its `@celo/...` dependencies need to be published. If there have been any changes in the package directory itself, or in any of its dependencies since the last publish, it needs to be published.
3. Starting at the lowest level dependency that needs to be published and working up to the package you intended to publish:
a. Set the version that should be published. In most cases this will just be removing the `-dev` from the version, but it could be incrementing at the `major` or `minor` level
b. Build + publish the package with npm, tagging with the latest commit _in that directory_
c. Increment the `patch` version and add `-dev` to it
d. Update higher level packages' dependencies to be the published version
4. Update _all_ `package.json`s that use `dev` versions to the latest `dev` version for all packages that got published.
5. Make a commit for the resulting version changes. Version changes should be the _only_ thing in the commit.


**How do we determine if there's been changes since the last publish?**
This relies on having tagged with the commit hash. If this is happening reliably, we can get the 2 most recent commit hashes for the directory. For example, let's say they are:
`aaaaaa` and `bbbbbb`
If the difference between these two is _only_ version bump(s) in `package.json`, it's likely that we don't need to publish. 
We'll need to confirm that, though, by checking if `bbbbbb` has been published. We can do with this command: `npm view .@bbbbbb version`
If it returns nothing, the changes in `bbbbbb` have not been published (not with the tag anyway).
If it returns a version, we can compare that with what's currently in `package.json` and confirm that the only difference is an incremented patch version + `-dev`
