### ISSUE TITLE
Consider allowing users to revoke votes from ongoing proposals

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#2836]
During the governance exercise in Baklava, at least two users voted, then were surprised that they could not unlock their gold. The solution to the surprise is to make sure it is well documented both on the official docs page and in the CLI. In addition to that we should consider allowing suers to revoke votes from an ongoing governance proposal so that they can begin to withdraw funds. This will become more crucial when the referendum stage may be multiple days as users who cannot afford the risk of increasing their unlocking time to `time to end of voting + unlock period` will be disincentived from voting.

**Comment by yorhodes** [comment]
some clarifying notes
[`LockedGold.unlock` is blocked on `Governance.isVoting`](https://github.com/celo-org/celo-monorepo/blob/6d9bbde1bd4eebbeaa5460a2cbf60ed8f00dbd3e/packages/protocol/contracts/governance/LockedGold.sol#L171-L172)
`Governance.isVoting` uses an account's single upvote to check if the voter is voting on the queue, and the most recent referendum proposal to check if the voter is voting on the dequeue ([is this proposal in referendum](https://github.com/celo-org/celo-monorepo/blob/93d7f545b4d71772f9be3975eb77732da55f9331/packages/protocol/contracts/governance/Governance.sol#L769))
Revoking the single upvote is already supported
Simply revoking a referendum vote would break our `isVoting` check when the most recent referendum proposal is not the only referendum proposal being voted upon in the dequeue
However, we can safely unvote all of the dequeue referendum proposals at once by enumerating all of the dequeued proposal indices and [decrementing the stored voter record](https://github.com/celo-org/celo-monorepo/blob/93d7f545b4d71772f9be3975eb77732da55f9331/packages/protocol/contracts/governance/Governance.sol#L59), and subsequently zeroing the most recent referendum proposal
Care should be taken to use the [stored vote record weight](https://github.com/celo-org/celo-monorepo/blob/93d7f545b4d71772f9be3975eb77732da55f9331/packages/protocol/contracts/governance/Governance.sol#L51) rather than the [canonical voter weight](https://github.com/celo-org/celo-monorepo/blob/93d7f545b4d71772f9be3975eb77732da55f9331/packages/protocol/contracts/governance/Governance.sol#L629), and the [proposal's network weight should be updated](https://github.com/celo-org/celo-monorepo/blob/93d7f545b4d71772f9be3975eb77732da55f9331/packages/protocol/contracts/governance/Governance.sol#L641)

**Comment by yorhodes** [comment]
Closed by https://github.com/celo-org/celo-monorepo/pull/7611

**Comment by yorhodes** [comment]
Closed by https://github.com/celo-org/celo-monorepo/pull/7611
