### ISSUE TITLE
Create a self-contained self-validating number input component

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#29]
Expected Behavior
A nicely self-contained, reusable component that can clean it's own input

Current Behavior
Logic to clean input is spread across parent component (sendAmount, exchangeAmount)
See #4414

Looks like we already have two components for this, let's audit those see if they can be modified to fit the job:
https://github.com/celo-org/celo-monorepo/blob/master/packages/react-components/components/NumberInput.tsx
https://github.com/celo-org/celo-monorepo/blob/master/packages/react-components/components/PhoneNumberInput.tsx

See here too: https://github.com/celo-org/celo-monorepo/blob/master/packages/mobile/src/send/LabeledTextInput.tsx#L37

**Comment by isabellewei** [comment]
related: #82

**Comment by drklee3** [comment]
Note related to decimal inputs:  For currencies, an input that goes right to left (e.g. type 2 for 0.02, 228 for 2.28) may be preferable to the current normal text input.  However, this is difficult to implement as there is an excessive amount of "flickering" when reformatting.  This is because the normal way of validating and formatting a text input is asynchronous via a component's state and the value prop which occur after a user inputs characters, without a way to prevent user input from showing or formatting before display.

For example if an input has `0.02`.  Inputting another `2` will result in `0.022` for a brief second then `0.22` will show.  Input of 8 shows `0.228` then `2.28`.

The only method I believe that would prevent such flickering is to implement a native module so that text formatting is done before a user's input shows at all in the text input.
