### ISSUE TITLE
[Wallet] Creating wallet with wrong PIN

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2933]
### Preface
While I was fixing https://github.com/celo-org/celo-monorepo/pull/2932, I've discovered the follwoing:
1) We ask user to type PIN and then confirm
2) We store this PIN in cache
3) Creating account
     a. If PIN is **still in cache** we are using it to store private key on disk
     b. If PIN is **not in cache** anymore (app closed or timeout) we ask user to enter the PIN and using it to store private key on disk.
https://github.com/celo-org/celo-monorepo/blob/1b5b5aeca366e0873b22abb0abe222de9e3bd7a4/packages/mobile/src/web3/saga.ts#L190-L200

### Expected Behavior

In step `3b` we should use the same PIN, user entered earlier or again ask **two times** to ensure, that user did not do a mistake.

### Current Behavior

In step `3b` we are using whatever PIN user has entered discarding previously entered PIN.

**Comment by i1skn** [comment]
Possible solution I see - ask user to enter PIN only after verifying invite code/restoring from words.

**Comment by tarikbellamine** [comment]
@i1skn can this be closed?

**Comment by i1skn** [comment]
No, this is still an issue.

**Comment by gnardini** [comment]
I can't reproduce this, is this still possible after the komenci flow changes? The account is created immediately after setting the PIN, so there doesn't seem to be much room to cause this issue. I tried commenting out the account creation after setting the PIN and restarting the app so that the cache is clean, but the user starts from the education screen in that case, so they have to enter their PIN and confirm it again.

**Comment by i1skn** [comment]
I will double check if I can still reproduce it

**Comment by i1skn** [comment]
This issue has been fixed with the changes to onboarding flow, cause we are creating an account immediately after setting the PIN now as @gnardini pointed out.
