### ISSUE TITLE
[Wallet] Users SBAT turn off data saver on iOS

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#2985]
### Expected Behavior

Users can turn off data saver on iOS on a default geth build of the app

### Current Behavior

When users toggle data saver off, the app restarts but data saver is still on

**Comment by Lss-Ankit** [comment]
@jmrossy  Verified with App version: Test flight v1.6.2(24) on iPhone 7+( 13.3.1), iPhone 5S(12.41.)
and found the root cause of when this issue is repro. 
**Pre-condition**: Make sure Data Saver toggle is ON.
**Repro Steps:**
1. Tap on Settings option. 
2. Select Data Saver. 
3. Toggle off the Data saver. 
4. Repeat Steps 1 - 3 for two-three times. 
5. Observe.

**Attachment:** [iOS_DataSaverToggleOFfNotWorking.mp4](https://drive.google.com/open?id=1ZuAF3wAY3WOq4-ZHSAsP0g8u4Mj9sbv-) (Bug observe at 17 sec)
