### ISSUE TITLE
Developers SBAT know that the oldest oracle report used by CP-DOTO hasn't expired

### ISSUE THREAD

**Issue by clrblmt** [celo-org/celo-monorepo#299]
### TODO

Check the oldest report isn't expired. If the oldest report *is* expired, `shouldUpdateBuckets()` should return false. 

Note (from sprint planning Dec 18): This does not need to remove expired reports from `SortedOracles`. Just avoid updating buckets if some reports are too stale.

**References:**
[Exchange.sol](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/contracts/stability/Exchange.sol)
` function shouldUpdateBuckets() private view returns (bool) `

**Comment by yerdua** [comment]
What exactly should happen here? I'm assuming that the ideal case is that an expired report is not affecting the median, and therefore isn't used to set the buckets.

Currently, every function in the path for getting the updated buckets is a `view` function. In order to remove expired reports and stop CP-DOTO from using them, `removeExpiredReports` in `SortedOracles.sol` needs to be called. This is a function that requires gas.

**Comment by BatiGencho** [comment]
@asaj Reserved for Ventsi @Limechain
