### ISSUE TITLE
[Wallet] Doubled "Payment received" notifications

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#2998]
### Expected Behavior

User receives only one notification per payment

### Current Behavior

Sometimes I got two notifications

### Screenshots
![IMG_8070](https://user-images.githubusercontent.com/6160124/75562290-4995ef80-5a83-11ea-8b7b-0bfe4e8b2909.jpeg)
![IMG_8072](https://user-images.githubusercontent.com/6160124/75562294-4b5fb300-5a83-11ea-937a-7c5d0c294f24.jpeg)

**Comment by jmrossy** [comment]
This happens because there are two versions of the notification service running at once, causing possible race conditions where we send notifications twice.

We've seen this before on occasion through no fault of our own. It's an AppEngine bug where sometimes deploying the service doesn't properly stop the last version.

For posterity: if we ever see this, go to the App engine versions page and ensure only the latest is running.
