### ISSUE TITLE
Blockscout /admin Open

### ISSUE THREAD

**Issue by henry-zhang-bohan** [celo-org/celo-monorepo#3173]
### Expected Behavior
Users shouldn't be able to access https://alfajores-blockscout.celo-testnet.org/admin/setup and the equivalent of baklava & integration. /admin should be blocked

### Current Behavior
White-hat hackers have reported this issue three times now for being able to access the /admin page.

**Comment by aaitor** [comment]
This issue was discussed in the #protocol-tools planning with @diminator & @nambrot . The agreements are:
* We can block this in NGINX avoiding external users to get access to the blockscout `/admin` URL and at the same time we expose that admin interface via internal K8s routing internally to Celo staff
* We move this to #infrastructure with a low priority
