### ISSUE TITLE
Make the ContractKit a fully Typescript lib

### ISSUE THREAD

**Issue by gastonponti** [celo-org/celo-monorepo#3515]
### Expected Behavior

ContractKit working with types since the package install, without hacky solutions.

### Current Behavior

ContractKit is a javascript library, and for using types the user have to add some lines to the `tsconfig.json` to search for the specific types that the contractkit overrides.
in the tsconfig:
```
"include": ["src", "./node_modules/@celo/contractkit/types"]
```

**Comment by annakaz** [comment]
Fyi this is an issue that Moonpay encountered during their integration

**Comment by annakaz** [comment]
Adding error messages to make it easier to search for errors caused by this issue: 
`node_modules/@celo/contractkit/lib/generated/Accounts.d.ts:5:10 - error TS2305: Module '"../../../../web3-core-helpers/types"' has no exported member 'Callback'.`
and
`node_modules/@celo/contractkit/types/web3-celo.d.ts:7:5 - error TS2717: Subsequent property declarations must have the same type.  Property 'value' must be of type 'string | number | BN', but here has type 'string | number | BigNumber'.
7     value?: number | string | BigNumber
      ~~~~~
  node_modules/web3-core/types/index.d.ts:122:5
    122     value?: number | string | BN;
            ~~~~~
    'value' was also declared here.
`

**Comment by aaronmgdr** [comment]
This has been addressed

**Comment by aaronmgdr** [comment]
Complete
