### ISSUE TITLE
Pay request shows invalid total amount in some cases

### ISSUE THREAD

**Issue by timmoreton** [celo-org/celo-monorepo#36]
### Current Behavior

When opting to pay X's request the below total amount showed as 0. After requesting a payment from someone and going through with that and then opening the pay request from X's again it is now showing the total correctly.

![Screenshot_20190716-111958](https://user-images.githubusercontent.com/6825447/61381168-f2079280-a8aa-11e9-97eb-42c179aeb888.jpg)

**Comment by jeanregisser** [comment]
After investigating I found this problem is present when `suggestedFee` (from the redux store) is still an empty string. i.e. when the `updateSuggestedFee` action hasn't been called yet.

From what I see, `updateSuggestedFee` is called from two places:
- in `<SendAmount />`
- when a `PAYMENT_REQUESTED`(push) notification is received when the app is not already opened.

Since the notification service is currently disabled on alfajores. There is no chance for the fee to be set unless the user navigates to a screen using `<SendAmount />`.

A simple fix would be to add another call to this action at the appropriate place.

I feel there might be a more future proof approach to this.
I'm missing enough context on this and I will discuss it with whoever knows more or wrote the initial logic. 

cc @cmcewen @jmrossy

**Comment by isabellewei** [comment]
I think this might be solved by #83

**Comment by jeanregisser** [comment]
Thanks for digging this @isabellewei!

I also found https://github.com/celo-org/celo-monorepo/issues/113 which is contradicting this.

I usually try to keep things out of redux unless necessary. Here, one argument in keeping the fee result in redux would be if another saga would need access to it.
However as I understand it now, the fee is something that isn't really global and depends on the recipient and amount at least (and type of token Celo Gold or Celo Dollar) so it shouldn't be stored globally like it's done currently.

@martinvol could you help me understand the whole picture?

**Comment by martinvol** [comment]
Yes, you're right. The fee should not be in the global store as it's only useful in the payments flow, what's more, if you notice it's implemented using thunk instead of saga.

It doesn't really hurt to have it the store but it'd be nice to take out.

As you said, this issue would be fixed by some sort of entry point that triggers `updateSuggestedFee` before showing the user the SendConfirmation screen.

This could be combined with the effort in splitting SendAmount to a new SendAmount and SendInvite.

**Comment by jeanregisser** [comment]
Thanks @martinvol, I'm gonna take it out of redux for now and update it on demand where it's needed. 

Probably wrapping this in a helper component.
