### ISSUE TITLE
Ensure better transaction delivery/reduced errors in wallet from celo-blockchain

### ISSUE THREAD

**Issue by cmcewen** [celo-org/celo-monorepo#3654]
### Current Behavior

https://sentry.io/organizations/celo/issues/1622975213/?project=1250733&query=is%3Aunresolved
https://sentry.io/organizations/celo/issues/1526588141/?project=1250733&query=is%3Aunresolved

**Comment by nategraf** [comment]
Looking at the two issues linked from Sentry:

> gas required exceeds allowance (20000000) or always failing transaction
> https://sentry.io/organizations/celo/issues/1622975213/?project=1250733&query=is%3Aunresolved

This one is a transaction that was never sent because it failed during estimation. The reason isn't included here because it's an older version of the app, but based on more recent failures, this is likely either an expired attestation request or an operation that would overdraw a cUSD account.

> Failed to check for transaction receipt: {}
> https://sentry.io/organizations/celo/issues/1526588141/?project=1250733&query=is%3Aunresolved

This one is an exception within web3.js on the call to get the transaction receipt, although I don't understand why the error is empty. Best here would be to handle this error and try calling `getTransactionReceipt` manually. https://github.com/ethereum/web3.js/blob/dd4c8ecc07af7f801c2ef2bca8ed2e7c57687546/packages/web3-core-method/src/index.js#L276-L290

**Comment by tarikbellamine** [comment]
@nategraf should this still be open?

**Comment by nategraf** [comment]
So the `Failed to check for transaction receipt: {}` is still an issue, and actually the leading cause of transaction failures, but I think this GH issue has outlived it's usefulness.
