### ISSUE TITLE
Devs SBAT reference and fix issues from slither static analysis

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#372]
### Expected Behavior

Issues exist for report from https://github.com/crytic/slither
[report.txt](https://github.com/celo-org/celo-monorepo/files/3478101/report.txt)

### Current Behavior

No issues

**Comment by yerdua** [comment]
Still unaddressed:

**"dangerous strict equality"** 
I don't see a non-strict-equality way of performing the check here.
- [ ] Escrow.revoke (identity/Escrow.sol)

**"contract locking ether":** "Contract X has payable functions but does not have a function to withdraw the ether"
- [ ] Exchange: stability/Exchange.sol
- [ ] Reserve: stability/Reserve.sol

**"unused return"** "ignores return value by external calls" - In these cases, the return value doesn't seem important?
- [ ] Exchange.exchange (stability/Exchange.sol)
- [ ] Reserve.mintToken (stability/Reserve.sol)

**"public function that could be declared as external"** - for most of these, it was a simple change. For these remaining ones, changing `public` to `external` resulted in an error about "calldata"
- [ ] MultiSig.initialize (common/MultiSig.sol)
- [ ] MultiSig.submitTransaction (common/MultiSig.sol)
- [ ] GetSetV1.set (common/test/GetSetV1.sol)

Other issues:
- There's a bunch of items referencing BondedDeposits, but that no longer seems to exist. What happened to that, and are any of those issues still relevant?
- `Reentrancy in Validators.revokeVote (governance/Validators.sol#489-521)` - this function doesn't exist in that file anymore. Was it renamed or moved?


The PR with the fixes so far is here: #572
@m-chrzan @asaj - can I get your insight on the remaining issues?

**Comment by m-chrzan** [comment]
Thanks for all the work on this!

>"contract locking ether"

In the case of the Reserve, this is probably just due to slither not picking up on our precompiled ERC20 Gold contracts. It is possible to transfer Gold out using `transferGold`.

I think the fact that we have a payable fallback in the Exchange was a workaround for some issue we had before, not sure if it's still necessary. Either way, this is not critical since these contracts are proxied, so it would be possible to free up any locked up gold via code upgrade.

>"unused return" "ignores return value by external calls" - In these cases, the return value doesn't seem important?

Agree, not super important. But probably good practice to follow common conventions.

>"public function that could be declared as external"

Hmm, fortunately neither of these are in use in the core system, but that behavior is very weird. Where did these calldata errors happen? Compilation, stack trace in unit tests?

>BondedDeposits

Renamed to LockedGold, see #653 

>Validators.revokeVote 

I still see it on master, can you double check?

**Comment by yerdua** [comment]
>> "public function that could be declared as external"

> Hmm, fortunately neither of these are in use in the core system, but that behavior is very weird. Where did these calldata errors happen? Compilation, stack trace in unit tests?

These errors showed up in VS Code. After changing "public" to "external", the param `address[] memory _owners` gets highlighted as having an error: `Data location must be "calldata" for parameter in external function, but "memory" was given.`
That same error also shows up during compilation.

> > Validators.revokeVote

> I still see it on master, can you double check?

Found it. Not sure how I missed it.

**Comment by m-chrzan** [comment]
> These errors showed up in VS Code. After changing "public" to "external", the param `address[] memory _owners` gets highlighted as having an error: `Data location must be "calldata" for parameter in external function, but "memory" was given.`
> That same error also shows up during compilation.

I think if you change the `memory` to `calldata` in the parameter it might start working.
