### ISSUE TITLE
“Placeholder” text is shown on Payment request notification section when user send payment request to  other user. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4031]
**Frequency:** 100%
** Repro App version:** Celo Integration build v1.8.2 (34)
**Repro on device:** iphone 6+ (12.4.5)
**Tested Account** 503 447 5958 / back up key
**Repro Steps:** 
1) Launch the app and login with tested account. 
2) Tap on Request button. 
3) Select any phone number 
4) Enter an amount. tap on review button. 
5) Enter Security PIN. 
6) Tap on request button. 
7) Navigate to Home tab and observe 
 
**Current Behavior:**  Placeholder Text is shown 
**Expected Behavior:** Reason of sent payment request should be shown
**Impact:** User B will not able to get reason why they receive payment request. 
**Attachment:** PlaceholderIssue.png
![PlaceholderIssue](https://user-images.githubusercontent.com/55572027/83943637-5f057d00-a81b-11ea-9cb3-2e41314c87d1.PNG)

**Comment by ValoraQA** [comment]
Hey @gnardini I have verified this issue using  latest Android internal build V1.15.1 & Test Flight build V1.15.1 & observed that issue is fixed now. User is able to see amount & description (if added) below waiting for section.
**Verified On Devices:**  iphone 6+ (12.4.5), iPhone SE (14.2), Redmi Note 8 (9.0)
Thanks..!!
