### ISSUE TITLE
[ContractKit] Accounts get stuck in web3 when reusing it's instance

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#4358]
### Expected Behavior

I use code like this to load a wallet from a mnemonic:

```
    const hdwallet = HDWallet.fromMnemonic(seed)
    const w = hdwallet.derive(`m/44'/52752'/0'/0`)

    const wallet = new LocalWallet()

    for (let x = 0; x < 5; x++) {
      const a = w.derive(x)
      wallet.addAccount(a.getPrivateKey().toString('hex'))
    }

    const kit: ContractKit = await newKitFromWeb3(web3, wallet)
```

When i reuse the instance of web3 multiple times in this code (for example when the seed phrase is changed) it will accumulate the accounts in web3 while they are not longer in the wallet.

So i have to recreate web3 every time which is pretty costly from a network perspective. 

```
    const web3: Web3 = new Web3(new Web3.providers.HttpProvider(config.rpcUrl));
    const kit: ContractKit = await newKitFromWeb3(web3, wallet)
```

### Current Behavior

When a web3 instance is use more than once the accounts get stuck despite being in the wallet anymore.

**Comment by mcortesi** [comment]
i don't fully follow.

The current object relationship are `kit -> web3js -> <provider>CeloProvider -> wallet`. 

Now, when you create a new `kit` it will replace (if needed) the web3.currentProvider with a celoprovider. Reusing the web3 can be problematic; since there's a semantic relation of `kitInstance -> wallet`; but in fact that relationship is `web3 -> ... -> wallet`. So reusing web3 means reusing the wallet.

I guess you could reuse the `http provider` if that saves network resources.. but not sure it actually does. For a websocket/ipc one, maybe.

**Comment by H34D** [comment]
> The current object relationship are `kit -> web3js -> <provider>CeloProvider -> wallet`

Unfortunately this relationship is not visible to the consumer of contract kit and therefore a little surprising. 

> I guess you could reuse the `http provider` if that saves network resources.. but not sure it actually does. For a websocket/ipc one, maybe.

Thats a great idea, will try this out. thanks!

**Comment by H34D** [comment]
I tried this out and it works. Closing this issue because i do not expect any change on this behaviour. Leaving this here for documentation ;)
