### ISSUE TITLE
[ContractKit] add removeAccount function

### ISSUE THREAD

**Issue by H34D** [celo-org/celo-monorepo#4359]
### Expected Behavior

When i am able to add an account it would be good to be able to remove the account as well. This enables cycling of accounts. 

https://github.com/celo-org/celo-monorepo/blob/b4632d2eb40b5f6fb9cf35463b5c08ec338d418c/packages/contractkit/src/wallets/local-wallet.ts#L10
https://github.com/celo-org/celo-monorepo/blob/b4632d2eb40b5f6fb9cf35463b5c08ec338d418c/packages/contractkit/src/kit.ts#L193

### Current Behavior

It is not possible to remove an account once added without recreating web3 and the whole contract kit

**Comment by mcortesi** [comment]
This could be added.

Something we consider when thinking about this is that on web3.js you can use `acccount indexes`. So for example, if you do `eth.accounts()` and the sign a tx and specify `from: 0` it will use account index `0`.

By doing add/removes we mess with that semantics. That's one of the reasons for ledger wallet it's a constructor parameter.

On hindsight, probably we don't need to be this cautious. Since this can already happen when you connect to a node and accounts are being added to the node.
