### ISSUE TITLE
Support flexible usage of the Celo blockchain client as a light client or signer-only

### ISSUE THREAD

**Issue by nategraf** [celo-org/celo-monorepo#4436]
### Description

Using the mobile app in data-saver / forno mode requires running a celo-blockchain node to continue running and syncing to the network. It should be possible to use the `celo-blockchain` signer functions without continually syncing to the network and consuming unnecessary resources.

**Comment by bowd** [comment]
I thought I was on to something but I've actually been having trouble implementing a `geth signer` subcommand that would start `geth` in a stripped down signer only mode. I need some advice on this, so I'll outline my current exploration.

The goal was to start a version of `geth` that implements `personal_UnlockAccount` and `eth_SignTransaction` RPC methods, but doesn't do much else. I started by diving into how the RPC services are registered and I saw that they are tied to the Ethereum service depending on what type of node you're running, [light ethereum service](https://github.com/celo-org/celo-blockchain/blob/master/les/client.go#L219) or in the [full node](https://github.com/celo-org/celo-blockchain/blob/master/eth/backend.go#L315). These services are then attached to the main `node` object based on [the config](https://github.com/celo-org/celo-blockchain/blob/master/cmd/utils/flags.go#L1694-L1713). 

Then these are all started/managed as part of the `node` [lifecycle](https://github.com/celo-org/celo-blockchain/blob/master/node/node.go#L165-L292). Which actually [starts the whole p2p server](https://github.com/celo-org/celo-blockchain/blob/master/node/node.go#L192), and the other registered services.

My initial exploration was to add a new service at the same level as the light ethereum service and the full node service, called a signer service that does part of the things the regular services do (like setting up the account manager) and implements a lot of dummy backends for the other methods from the `api_backend` implementation that act as the basis for the `ethapi` that we need to pull in to have the `eth_SignTransaction` method. This can be seen on [this branch](https://github.com/celo-org/celo-blockchain/compare/bowd/signer-mode?expand=1). 

This approach mostly works but it doesn't reduce the node usage that much because the backbone of the networking gets initialised in the `node.Start` method which starts the p2p service irrespective of what Services are added to the node. Initially I thought I would be able to disable most things by just not `Register`-ing services to the stack but that doesn't seem to be the case for most of the networking functionality. 

This means that we can't really use the backbone of the geth command (`node.Node`) if we want to start it in a stripped down mode, but if we don't make use of that then we can't easily setup the RPC system and everything else without duplicating a lot of code, or at least that's my current feeling.

@kevjue, @mcortesi, @nategraf - I'd love some more input on this. I should have reached out sooner but I didn't manage my time well enough and kept jumping between things without much progress ☹️.

I'm now considering @nategraf's suggestion of not running it as a node, but implementing this more as a library/utility function. I hope to have more input on that by the end of the day.

**Comment by bowd** [comment]
I've also implemented [this option](https://github.com/celo-org/celo-blockchain/compare/bowd/signer-cmd?expand=1) which has a geth subcommand `sign-tx` that takes two params: json dump of the tx and the passphrase that should unlock the `from` account of the tx, and outputs the signed transaction to stdout. Example:

```bash
❯ go run ./cmd/geth sign-tx '{"nonce": "0x0", "from": "0x9269440FCE503b67565A5f1A4192924aDB35c70A", "to": "0xd3CdA913deB6f67967B99D67aCDFa1712C293601", "value": "0x0", "data": "", "gas": "0x12334", "gasPrice": "0x123"}' asd 2>/dev/null
{"raw":"0xf868808201238301233480808094d3cda913deb6f67967b99d67acdfa1712c2936018080830149fca085359e22cc3a4782b51d24abb25393e455aa8ba32e64d9e97c92134cf983ddbfa0796eabb97fce7e1d1d422b7e7c4723bb3952a035169adc313b094c3472ebfc03","tx":{"nonce":"0x0","gasPrice":"0x123","gas":"0x12334","feeCurrency":null,"gatewayFeeRecipient":null,"gatewayFee":"0x0","to":"0xd3cda913deb6f67967b99d67acdfa1712c293601","value":"0x0","input":"0x","v":"0x149fc","r":"0x85359e22cc3a4782b51d24abb25393e455aa8ba32e64d9e97c92134cf983ddbf","s":"0x796eabb97fce7e1d1d422b7e7c4723bb3952a035169adc313b094c3472ebfc03","hash":"0xb7bfd04a8bd483f436daa812b14dfa498dbf60cbd499f3b567b3716d8df83476"}}
```

This works and can be easily integrated in the app I think, but it still is a bit ugly because I had to essentially _mock_ a backend in order to be able to reuse the `SignTransaction` from the `ethapi` and not reimplement that logic there.
I'm gonna also try to achieve the same result by using the signer api that Clef uses, which might be a bit more straightforward / less to mock there.
