### ISSUE TITLE
Moonpay Experience Improvements

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#4562]
### Expected Behavior

* 2 hamburger menus
* long time to load
* not as differentiated from the main experience
* back button kicks you out of the browser instead of taking you back a screen

### Current Behavior

What is the current behavior?

**Comment by annakaz** [comment]
Checked in with @coreycelo about the current flow: 
![Screenshot 2020-08-06 at 9 21 00 AM](https://user-images.githubusercontent.com/16907027/89556912-e85b1080-d7c6-11ea-9308-8bba83800851.jpeg)

> 2 hamburger menus

Double hamburger menu is removed

> back button kicks you out of the browser instead of taking you back a screen

Back arrow has expected behavior of going back a screen in Moonpay, and back button has expected behavior of leaving Moonpay flow

 >not as differentiated from the main experience

Decided the widget as is is the best option at the moment, it is in between leaving the app to go to a separate browser and having a built in flow

**Comment by tarikbellamine** [comment]
Feedback has been addressed
