### ISSUE TITLE
[Wallet] Import contacts failed banner shown, unclear if import actually failed 

### ISSUE THREAD

**Issue by annakaz** [celo-org/celo-monorepo#4683]
### Expected Behavior

No failed import contacts banner shown if import was successful

### Current Behavior

Failed to import contacts error banner after trying to import contacts on Android after verification. Still able to look up a phone number to send to

Fails with error:
`identity/contactMapping :: Error importing user contacts :: Unknown failure 400 in Error: Unknown failure 400`

See logs here
https://groups.google.com/a/clabs.co/g/support/c/Y7AyBNh9Gyg/m/q3hI-rxPBwAJ

**Comment by Lss-Ankit** [comment]
@annakaz i have verified an issue on latest Valora app build v1.0.0 (10) and found that issue is still reproduced. 

- "Failed to import contacts" error message is shown when user try to connect contacts after verifying phone number. 

Attachment: [Android_ContactImport_Failed.mp4](https://drive.google.com/file/d/1Nux6cFUl8YxIOO96gRBQUCiBq4oNPCjK/view?usp=sharing)

**Comment by annakaz** [comment]
Fixed by https://github.com/celo-org/celo-monorepo/pull/4694
