### ISSUE TITLE
“Date & time” is not shown on received CELO activity for IOS users when Android user send CELO to iOS users. 

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#4768]
**Frequency:** 100%
**Repro App version:**  Valora Mainnet build v1.0.0 (12), Test flight build v1.0.0 (11) 
**Repro on device:** iPhone 7+ (13.3.1) 
**Test Account:** 
**Repro Steps:**
1. Launch the Android app and sign in with a test account. 
2. Launch the iOS app and sign up. 
3. Tap on the Hamburger menu from Android device. 
4. Tap on CELO option. 
5. Tap on Withdraw CELO 
6. Scan IOS user QR code and sent CELO. 
7. Observe date and time is not shown for iOS user on received CELO 

**Current Behavior:** Data & time is not shown on received CELO activity
**Expected Behavior:**   Data & time should shown on received CELO activity
**Investigation:** Issue does not repro for Android user when they received CELO. 
**Impact:** User did not get idea when they received CELO. 
**Attachment:**CELOActivityIssue.png 
![Screenshot 2020-08-22 at 4 25 11 PM](https://user-images.githubusercontent.com/55572027/90954896-9274a280-e42d-11ea-887f-812bd0fe2f12.png)

**Comment by tarikbellamine** [comment]
@nityas what is expected behavior here?

**Comment by ValoraQA** [comment]
Hi @nityas I have verified this issue using latest  Android Internal Build V1.11.0(1004294337) & Test Flight Build V1.11.0(47) & observed that issue is fixed now. iOS user able to see Date & Time.
**Verified on Devices:** Samsung Galaxy A5(7.0), iPhone SE (13.4.1)
**Attachment:** [Date&TimeDisplaying.png](https://drive.google.com/file/d/1jN9WGaw-sxpxnv35Fr5XRZWiFa0fI8xD/view?usp=sharing)
