### ISSUE TITLE
remind link in 1.0.1 references celo.org/build instead of new short links

### ISSUE THREAD

**Issue by nityas** [celo-org/celo-monorepo#5020]
### Expected Behavior

reminder to invite link should contain vlra.app/ style shott links

### Current Behavior

remind link in 1.0.1 references celo.org/build instead of new short links

**Comment by jeanregisser** [comment]
I've checked this, and from what I see there's no issue anymore.
I believe the problem was an older invite sent before we changed to the `vlra.app` domain.

When we send an invite, the code and link are stored locally in the wallet. 
When the user taps on the action to remind the person, the previously stored code and link are used.

**Comment by jeanregisser** [comment]
Discussed on Slack with @asaj and explanation above seems correct. Closing.
