### ISSUE TITLE
Allow governance approver to revoke an approval

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#5051]
### Challenge Description
Governance approvers play an important role in sanity checking that governance proposals are not malicious before they are put for referendum. In the unlikely event that governance approvers later learn of a show-stopping issue, this ticket calls for the ability for the governance approver to revoke their approval, effectively preventing an execution of a proposal.

### Submission Requirements
- Add a `Governance#unapprove` function which sets `proposal.approved = false`
- Add a require during `execute` to check that the proposal is actually approved
- Adding unit tests that check that a call to `unapprove` during approval, referendum and execution stage will effectively prevent the execution of the proposal (likely will want to check that `proposal.approved == true` in `execute`
- Submit a PR and address PR review comments by core developers
- Have the PR merged

### Prerequisites
- Basic Solidity Knowledge
- Minimal Familiarity with Celo Core Contracts

### Time Expectation
- 6 hours

### Resources
- [Docs on Celo Governance](https://docs.celo.org/celo-codebase/protocol/governance)
- [Existing Governance approval unit tests](https://github.com/celo-org/celo-monorepo/blob/master/packages/protocol/test/governance/network/governance.ts#L1360:L1360)

### Expected Behavior

Governance revokeApproval implementation?

### Current Behavior

Unclear if we want to allow revoking approvals

**Comment by nambrot** [comment]
Why wouldn't we want to?

**Comment by nambrot** [comment]
cc @yorhodes @aslawson

**Comment by nambrot** [comment]
I was trying to see whether this would be a good bounty ticket. If I understand correctly, we should be able to have a function that sets approved to false. Right now only vote checks that a proposal is approved, should we add the same check to execute, effectively giving approvers a last minute veto function (instead of just suspending further voting)

**Comment by aslawson** [comment]
Oh that's an interesting consideration -- I think it should be included in the `execute` check too. The approver role is to ensure the execution is secure and doesn't expose vulnerabilities. So if at anytime approvers have reason to believe a proposal could be detrimental for network, they should be able to un-approve it.

I actually think this is a bit more complicated since the action would need to happen through the governance approver multisig, so any "unapproval" would also need 3 approvers to execute that transaction...i don't think there is a way a single approver can just rescind their approval and have any impact.

But still seems doable for a bounty if we provide clear expectations of what "unapproving" means in practice.

**Comment by nambrot** [comment]
Yeah, I don't think a single signer on the multisig should be able to veto, only the quorum of signers. If you agree, happy to make this a bounty as well

**Comment by aslawson** [comment]
Ya I think this is a good approach, sounds good. Let's just makes sure the bounty hunter has the right references to understand the multisig nature for testing :)

**Comment by aslawson** [comment]
> Actually here is another fun edge case, governance approvers could collude with some voter base to basically have them vote in the first minutes of referendum, the approver could then unapprove, preventing further votes on the proposal, until right before execution approving again

Options:

1. allow votes even if a proposal is unapproved
2. do more sophisticated tracking which increases scope
3. don't allow re-approval if its been "unapproved" (AKA unapproved means its automatically expired)

**Comment by deepakhb2** [comment]
@nambrot I can work on this issue and I understand requirement. Can I work on this issue?

**Comment by aslawson** [comment]
hey @deepakhb2 we wanted to get a consensus from the community of whether we feel approvers should be able to retract approval during both approval and referendum phase.

**Comment by deepakhb2** [comment]
Hi @aslawson, Yeah I got confused and later got to know from yorhodes. I didn't start on this issue.
