### ISSUE TITLE
Kliento or ContractKit

### ISSUE THREAD

**Issue by silentlight** [celo-org/celo-monorepo#5128]
I am building an indexer for Celo and was wondering which client is better ContractKit or kliento?
Can I use the same Celo Core Contracts on both clients or other has better support than other?
Also, I want to be able to query our archive nodes by height so I need to have ability to query contract data by height.
Thanks!

**Comment by barbaraliau** [comment]
@silentlight ContractKit is the primary client for building on top of Celo. Kliento is a subset of ContractKit, so Kliento will have less capabilities. For the majority of projects, we recommend using ContractKit.

**Comment by silentlight** [comment]
Thank you so much for the response @barbaraliau.
I am a little concerned about per height queries. For instance `GoldToken` contract has balanceOf method. I see that in Kliento it is possible to pass height to it but I don't really see that option in ContractKit. Am I missing something?

**Comment by yorhodes** [comment]
ContractKit does not support height specific queries and always uses `latest`.
This is because of the more stringent node requirements; namely, archive mode and pruning disabled to support these types of queries. 
We could look into adding support for this in ContractKit if widely desired.
You can also check out the [eksportisto](https://github.com/celo-org/eksportisto) or [blockscout](https://github.com/celo-org/blockscout) tools.

**Comment by silentlight** [comment]
Thanks @yorhodes. Any idea how much it would take to add support for height specific queries?
