### ISSUE TITLE
Handle transactiontimeouts due to user backgrounding the app 

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#5142]
During the request phase -- we make 3 onchain transaction with 45s timeouts.  About half of reported transactionTimeouts are actually due to users backgrounding the application during this time.  We should consider 

1. Investigate whether we can freeze the timers when the user is backgrounded or still handle the asynchronous results from the onchain request when they return to the app.
2. Report a different error that indicates the user backgrounded the app during this stage instead of transactionTimeout
3. Tell  user to not leave during the 2min timer

**Comment by timmoreton** [comment]
I wonder if when we receive a timeout, we first check the receipt to see whether the tx was actually sent. In almost all cases, it will be.

**Comment by aslawson** [comment]
> I wonder if when we receive a timeout, we first check the receipt to see whether the tx was actually sent. In almost all cases, it will be.

This does occur -- the timer is a race against an asynchronous request that is satisfied when it received the receipt, hash and confirmation

**Comment by nategraf** [comment]
In #5620 I am adding a "grace period" to the transaction timeout which helps avoid triggering a timeout in cases where the app becomes suspended while tyhe transaction is pending with the network. In those cases, when the app returns to the foreground, and the initial timeout fires, the flow will enter the "grace period" which gives it time to reconnect to the network (if it lost connection) and retrieve transaction receipts. I've tested this on an iOS simulator and it seems to address the main failure mode we are looking at here.

I'm not confident we should call this issue resolved yet because if the app becomes suspended during gas estimation, or more generally before it is sent to the network, this will still fail. As a solution to this, and other transaction sending issues, it may be useful to add a transaction pool to the send mechanism that allows for retries of each stage of the transaction send flow and provides a flow of information to the transaction feed as well. (This would be a higher-level compliment to the Geth transaction pool, which is concerned with making sure any transaction handed off to it reaches the network)

**Comment by etuleu** [comment]
Another suggestion from @jeanregisser, which I think would work well in addition to your fix is to ask iOS to give us 30s extra background time. That would make the experience seem "faster" because we can make progress on the transactions even if the app is backgrounded.

**Comment by nategraf** [comment]
I didn't have context on this, but this article is helpful: https://docs.microsoft.com/en-us/xamarin/ios/app-fundamentals/backgrounding/ios-backgrounding-techniques/ios-backgrounding-with-tasks#background_tasks_in_iOS_7

**Comment by aslawson** [comment]
Chatted with @nityas regarding pausing the timer during backgrounding -- we decided against this for now as it would add complex edge cases (eg what if the user returns after an hour and all their issuers are expired).  With @nategraf current updates, the worst case is they return after 2 minutes and they get the general timed-out model which would instruct them to restart, but if they return within the 2 minute window it would resume.

Hopefully the copy @etuleu added will also make it clear that users should stay on the screen.

If we later find they are still backgrounding for over 2 minutes, we can revisit pausing the timer. Along with the epic for a governance proposal to extend the expiry time to 1 day, we can reduce risk of edge case occurrences.

The only further work would be handling suspension during gas estimation which seems a bit separate from the backgrounding.  So I think we can probably close this ticket -- @etuleu @nategraf any additional thoughts? Is there already a ticket that captures the gas estimation suspension issue?
