### ISSUE TITLE
User redirected to feed screen when user taps on Edit button from Withdraw CELO Confirmation screen opened via deeplink

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#5801]
**Frequency:** 100%
**Repro on build version:** Test Flight build v1.5.0 (29)
**Repro on devices:** iPhone XR (13.2.2) , iPhone 11 (14.0)
Testing Account: (806) 459-1666 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0)

**Pre-condition:** launch the deeplink celo://wallet/pay?address=0xd13eee43e38f65fe3839bef6297928b43de38a02&amount=.1&token=CELO 

**Repro Steps:**
1. Launch the application & login with a test account.
2. Copy the given link and paste to Safari browser. 
3. Tap on Open button from "Open this page to valora" pop up
4. Make sure the Withdraw CELO screen is open.
5. Tap on the Edit button. 
6. Observed. 

**Current Behavior:**  User is redirect to feed screen 
**Expected Behavior:** User  should go back to the Withdraw CELO screen
**Investigation:** [Randomly] Unable to load … message is shown when user taps on edit button. 
**Impact:** User is not able to edit the Withdraw CELO amount. 
**Attachment:** [IOS_CELO_Edit_issue.mp4](https://drive.google.com/file/d/1U1AWutJrE4sNvvA5ZgVTXdCHBnPi_T2F/view?usp=sharing) (Bug Observed at 06 sec)

**Comment by ValoraQA** [comment]
Hi @gnardini We have verified the issue in latest iOS test flight build V:1.20.4 and Android internal build V:1.20.4 and observed following things.

- [x] Edit button has been replaced by '<' button
- [ ] If we click on '<' button it redirects user to home page instead of CELO screen

Attachment : [redirection_iOS.mp4](https://drive.google.com/file/d/1bJN0oMnLfHgWVB6vUpT3K2AMc41OXmYq/view?usp=sharing) , [redirection_android.mp4](https://drive.google.com/file/d/1bJ8uBeqJDwdkf0Tikaq6UsVWkH1p-9w7/view?usp=sharing)

**Verified on Devices:** iPhone 6+(12.5.4), OnePlus 7T(11.0)

**CC:** @jeanregisser
