### ISSUE TITLE
[Protocol Economics] On-chain circuit breaker

### ISSUE THREAD

**Issue by yerdua** [celo-org/celo-monorepo#5846]
### Expected Behavior

Risk to the reserve should be minimized in times of extreme price volatility, in a way that does not require coordination of all of the active oracles or for them to use the same implementation.

There should be an on-chain mechanism that identifies extreme jumps in price, and shuts down or limits trading in volatile conditions. This mechanism also needs a clear method by which the circuit breaker can reset.

### Current Behavior

Circuit breakers are currently implemented in the oracle clients. If the CELO/USD exchange rate changes beyond a certain threshold in a short period of time, the oracles will stop reporting and must be manually restarted. If all oracles do this, all of the on-chain price reports will expire within 5 minutes and in turn will stop CP-DOTO buckets from updating. While people can take advantage of an incorrect/out-of-date price, the impact of this is limited to the already-set-up buckets. If the price stabilizes before oracles are restarted, one-sided trading can eventually bring the on-chain exchange rate to that new price.

This approach assumes all active oracles are behaving in the same way, with a circuit breaker enabled. It requires that oracle operators coordinate with with each other in deciding when to restart.

### Definition of Done

There is an on-chain circuit breaker that is deployed on mainnet.

**Comment by tkporter** [comment]
Some questions & thoughts I have:

1. Should we circuit break by individual oracle or by the median?

So far I'm more in support of circuit breaking by the median instead of giving an oracle that reported a >x% change a forced cooldown

2. Should this circuit breaker be in `Exchange.sol` or `SortedOracles.sol`?

I think we need to decide whether we see the `SortedOracles` contract as its own independently functioning contract that `Exchange` is a consumer of, or if `SortedOracles` is a helper contract of `Exchange`.

I'm mostly in support of the former, mostly because other non-Exchange smart contracts should be able to rely on the oracle rates and they may have their own constraints, like not being able to tolerate a gap in reports. This would mean that the consumer SC would have to add its own requirement of what a "safe" report really is. This philosophy conflicts with the existing behavior where oracle clients themselves have circuit breakers and I'm curious to hear thoughts here

3. Should this limit trades or just not allow bucket updates?

I think we should be really careful about limiting trades. My intuition is that this could really affect stability, so I feel more in support of just not allowing bucket updates

4. How long of a cooldown period & how to recover?

I'd like to ideally see a governable cooldown period, and then once that's over oracles can come to a quorum on-chain whether or not to continue reporting

**Comment by zviadm** [comment]
Few thoughts that I have had around this:

First on point #3: I definitely agree that limiting trades seems not very useful. Considering CP-DOTO fees are significantly higher compared to other similar systems (i.e Uniswap is 0.3% vs 0.5% of CP-DOTO), i think keeping it always on as long as buckets aren't reset seems safe. 


For point #2: I think it would be better if oracles always continue to report their current rates on-chain. Right now there is no way to distinguish if oracle is down, simply because it is not running, vs if it stopped reporting because it detected some anomaly. 
I think it would be better to always report the data on-chain, that way it is clear that oracle itself is running. Decisions around anomalies and so on can just be made based on the on-chain data instead and it will be automatically more transparent. 

For point #4: My general question would be, how necessary is the circuit breaker in the first place? How dangerous would it be to always reset buckets as long as on-chain CP-DOTO rate is within 1-2% of the new rate after reseting the buckets, and to not reset buckets until that condition is met? 
Basically if bucket reseting logic is something as simple as: 
`<current celo bucket> / <current cUSD bucket>` within `<new celo bucket> / <new cUSD bucket>  +/- 2%`

While still keeping the same logic that buckets can be reset at most once every 5 minutes. 

Assuming reasonable arbitrageurs, on-chain price should follow oracle prices reasonable close anyways. And since bucket reseting happens only once every 5 minutes anyways, profit opportunity seems quite tiny even if you try to manipulate oracle prices every 5 minutes.  

This would simplify oracles, since all they need to do is just report the rates. This will also remove any need for coordination to turn off or turn on bucket updating. I would definitely be interested to know what potential dangers would you see in that approach and if we have any practical data or tests that we can run to see if such things are possible.

**Comment by martinvol** [comment]
@zviadm my argument in favor of an on-chain circuit breaker is that oracles can be compromised, and nothing stops an oracle from reporting a super low (or high price) and thus compromising the median of the reports. In this case in your proposal you'd update the the bucksets, but for a wrong price, and the reserve (or supply of cUSD) would be at risk.

**Comment by tkporter** [comment]
Maybe I'm misinterpreting your last sentence @martinvol but I interpreted Zviad's proposal as (in bad js-pseudocode):
```
let timeLastConsidered = 0

shouldUpdateBuckets() {
  if (currentTime - timeLastConsidered < 5 minutes) {
    return false
  }
  timeLastConsidered = currentTime
  const currentBucketRatio = currentCeloBucket / currentCUSDBucket) 
  const percentDifference = abs(currentBucketRatio - currentCeloUsdRate) / currentBucketRatio
  if (percentDifference < 0.02) {
    return true
  }
  return false
}
```

So it's almost like a really conservative circuit breaker that relies heavily on arb. I'm still gathering thoughts on this, but to me this feels like at that point it's more a pure CPMM model

**Comment by zviadm** [comment]
@tkporter yes something similar, probably instead of using timeLastConsidered, i would just use timeLastUpdated, and not reset it every time you enter the loop. So if you have say 7minutes of too large of a percentDifference, but it suddenly becomes small, buckets get updated immediately instead of having to wait another 5 minutes. 

As for comparing it to raw Uniswap, while 1-2% is a small adjustment, it is still a very important adjustment. If exchange didn't adjust the price at all, i think it would have higher overall losses due to arbitrage.

Example scenario: if price changes by just 0.5% in 5 minutes, there is no arbitrage opportunity. However, if it continues to change by 0.5% in 5 minutes over 20 minute time period, now that is a 2% difference and an arbitrage opportunity / loss for the reserve. But since exchange will adjust its price every 5 minutes, that will limit the arbitrage opportunity and minimize the loss. 

So this keeps the status quo that 'reserve' is only incurring losses when you have very sharp price movement in very short time periods (i.e. <5minutes). It doesn't introduce extra losses due to slower price movement over longer time periods.

**Comment by sissnad** [comment]
@zviadm chiming in with a few thoughts

**On point 3: Trading with Stale Tanks / Buckets**
With the current setup, a circuit break often results in a significant mismatch between the market price and the stale (i.e. not updated by oracle updates) on-chain price. During that period traders will take advantage of the mismatch. 

We have seen that stale on-chain price results in arbitrage losses. Of course this is only an issue if

- we consider the losses to be unacceptably high
- we fear this is an entry for an exploit

As long as trading is still possible these mismatches can result in arbitrage losses. This should be the case with the current approach as well as with your apporach of conditioned resetting. But I assume, your approach would reduce the life time of circuit breaks arbitrage opportunities.

Personally, however, I prefer to minimise potential losses or attack surfaces as far as possible. That is why my first intuitive reaction would be to pick a hard circuit breaker that stops trading with CP-DOTO. 

I agree, we have to think about the conflict of interest between stability mechanism and loss prevention. But IMO trading with stale tanks will not help to establish the peg as the mismatch between the on-chain price and the Celo/cUSD market price is not determined by the triangular relation that CP-DOTO tries to enforce to regain the peg. Therefore, I think trading with stale tanks will not help to regain the peg. But this is something I want and need to spend much more thought on. 

Here is a little mental model to illustrate why I think the peg is not regained during a depeg through trading with stale tanks

- Assume CUSD/USD = 1.5, i.e. CELO/USD > CELO/cUSD. Let's assume CELO/USD = 6 and CELO/cUSD = 4 after a significant price jump (e.g. >40%). The on-chain price lags behind and tanks are not updated due to a soft circuit break or some resetting logic.
- Traders will take advantage of the lower on-chain price moving it towards 4 by buying cheaper Celo on-chain and selling it in the open market.
- These trades increase the Celo supply and decrease the cUSD supply in the market. Market CELO/cUSD will decrease as it is sensitive towards Celo and cUSD supply. Celo/USD should decrease to as it is sensitive to Celo supply, but less, as it is sensitive only towards one of the above factors.
- If assumptions about price sensitivities are true and the open market is efficient (= arbitrage within the CELO - cUSD - USD triangle is settled quickly), cUSD/USD will not decrease.

**Comment by sissnad** [comment]
@zviadm some more thoughts...

**On point 4:** 
I really like the autonomy of your approach of conditioned reseting. No intervention is needed to reactivate the updating (or trading).

There are a few things I would like to understand: 

- How often would your approach have been triggered compared to the current? As a simple backtesting analysis we could pull historical tank / bucket updates and test the resetting logic of your approach.
- What is the effective threshold in the current approach, i.e. what events, market moves cause all reports to expire stopping the updating of the buckets?
- The delay in the oracle pipeline causes delays between the on-chain price and the market price. This creates arbitrage opportunities. I am wondering whether, the resetting logic of your approach  halts the update of the buckets more often and creates even more on-chain/off-chain delays that result in more arbitrage opportunities and a higher aggregated losses across time? In other words, will your approach increase the mismatch and therefore the potential arbitrage loss even further?
- Would the resetting logic weaken the the stability mechanism, i.e. our requirement to create suffiecient arbitrage opportunity in case of a depeg? The limiting condition will also limit the range of intentional mismatch in case of a depeg.
- Future requirements towards CP-DOTO might me much more aggressive. This will increase arbitrage profits which will increase the profitability to manipulations. If we manage to come up with a reasonable backtesting analysis,it would be interesting to rerun the analysis with larger bucket sizes e.g. 2.5% reserve fraction to get a basic understanding.

I will calculate the potential arbitrage loss for a single event. This price jump actually happened when the coinbase listing was announced. With a hard circuit breaker that stops trading these losses would not have not occured.

- Assume market price is initially at  2.9  (Celo/USD) and that Celo tank / cUSD tank = 2.9 as well. Then we have a market price jump to 4.15 during which cUSD/USD stays at 1. 
- The tank will not be updated (4.15/2.9 > 2%) but traders will take advantage of the arbitrage opportunity. 
- If traders are alert and have sensitive bots they can take the profit in one update cycle. If the initial Celo tank = 270000 and cUSD tank = 783000, the arbitrage trades will change the Celo tank = 225704 and the cUSD tank =936670. 
- The corresponding transaction (44296 Celo, 153670 cUSD) happened at an average price of ~3.47. Traders can make a profit of 4.15 * 44296- 153670 = 30158 USD. 
- If the reserve fraction is increased from 0.05% to 2.5% the potential profit increases to 150795 USD.

**Comment by zviadm** [comment]
> @zviadm some more thoughts...
> I will calculate the potential arbitrage loss for a single event. This price jump actually happened when the coinbase listing was announced. With a hard circuit breaker that stops trading these losses would not have not occured.
> 
> * Assume market price is initially at  2.9  (Celo/USD) and that Celo tank / cUSD tank = 2.9 as well. Then we have a market price jump to 4.15 during which cUSD/USD stays at 1.
> * The tank will not be updated (4.15/2.9 > 2%) but traders will take advantage of the arbitrage opportunity.
> * If traders are alert and have sensitive bots they can take the profit in one update cycle. If the initial Celo tank = 270000 and cUSD tank = 783000, the arbitrage trades will change the Celo tank = 225704 and the cUSD tank =936670.
> * The corresponding transaction (44296 Celo, 153670 cUSD) happened at an average price of ~3.47. Traders can make a profit of 4.15 * 44296- 153670 = 30158 USD.
> * If the reserve fraction is increased from 0.05% to 2.5% the potential profit increases to 150795 USD.


just a quick note re: arbitrage losses. When such huge price jumps happen, reserve's actual value can change by 10s of millions of USD. So the arbitrage losses seem pretty irrelevant for reserve's health compared to actual reserve's balances that are held in CELO. (if price of CELO increases sharply, reserve gets healthier so these losses are easily offset, if price of CELO drops sharply by ~2x then Reserve will take huge amounts of losses due to that price movement, so arbitrage losses would be negligible compared to that).

at a high level, re: minimizing opportunities for malicious manipulation or larger losses. I think simplicity is the key. Imo, exceptional cases like a specialized circuit breaker that never really triggers, sounds quite scary because it is harder to foresee what can be consequences of it would be when it does actually trigger. 


------------

As for back-testing, calculating potential losses/gains retroactivately would be quite difficult because there are a lot of variables in there that you can't get historical values for (like depth of liquidity on CEXes). 

But backtesting for price movement percentages when bucket updates happen sounds like a good idea. That should be pretty easy and you can get historical price movements on bucket change boundaries and get some sort of a breakdown/histogram of that data fairly easily.

**Comment by zviadm** [comment]
I was pretty curious about price movement data between bucket updates so I wrote a quick script:
https://gist.github.com/zviadm/8071061a56b7d80537408a1aa49a850b

Output if you want to analyze: [ratechanges2.txt](https://github.com/celo-org/celo-monorepo/files/5667673/ratechanges2.txt)

This is what the breakdown looks like:
```
Number of bucket updates, where price movement is:
<1%:   45382
<1.5%: 1002
<2%:   251
<2.5%: 100
<3%:   26
<3.5%: 19
<4%:   17
<4.5%: 11
<5%:   8
>=5%:  32
```

**Comment by sissnad** [comment]
Nice! Thanks. 
Quick questions on your script. What is `concurrentMap`? Did you use an archive node to get past states? (And how did you make the top-level awaits work?)

I need to spend some more thoughts on it. But from the results I would prefer 
- a higher threshold (maybe 5%) 
- and a hard circuit breaker that stops trading with CP-DOTO.

I am also wondering whether it is better to use the return value of updated buckets (i.e. last updated and upcoming updated buckets) or the return value of upcoming updated buckets and buckets in prior block. Another idea could be to have multiple levels of halting durations (see e.g. https://cdn.cboe.com/resources/release_notes/2020/CFE-Enhancements-to-MWCB-Halt-Duration-Notice.pdf, https://www.nyse.com/publicdocs/nyse/NYSE_MWCB_FAQ.pdf)

>As for back-testing, calculating potential losses/gains retroactivately would be quite difficult because there are a lot of variables in there that you can't get historical values for (like depth of liquidity on CEXes).

Yes, it's not feasible to calculate losses that would have happened. But I still believe converting arbitrage trades into cashflows by using for example simple bid/ask prices is a useful proxy and indicator when comparing approaches or assessing the performance of trading / market making of CP-DOTO. Of course, you cannot read those loses as realised losses.



>at a high level, re: minimizing opportunities for malicious manipulation or larger losses. I think simplicity is the key. Imo, >exceptional cases like a specialized circuit breaker that never really triggers, sounds quite scary because it is harder to >foresee what can be consequences of it would be when it does actually trigger.

I am also very much in favour of a simple setup.

> just a quick note re: arbitrage losses. When such huge price jumps happen, reserve's actual value can change by 10s of millions of USD. So the arbitrage losses seem pretty irrelevant for reserve's health compared to actual reserve's balances that are held in CELO. (if price of CELO increases sharply, reserve gets healthier so these losses are easily offset, if price of CELO drops sharply by ~2x then Reserve will take huge amounts of losses due to that price movement, so arbitrage losses would be negligible compared to that).at a high level, re: minimizing opportunities for malicious manipulation or larger losses. I think simplicity is the key. Imo, exceptional cases like a specialized circuit breaker that never really triggers, sounds quite scary because it is harder to foresee what can be consequences of it would be when it does actually trigger.

I agree with you that arbitrage losses will be small compared to reserve portfolio value changes. But I think this is no reason to ignore them or not try to minimise them. Reserve value changes due to sudden price changes are market risks that the reserve will not be able to hedge. But the arbitrage losses due to a price change are specific to the setup and can be tuned. CP-DOTO is a little bit like a trader who is a bit too lazy to check market prices when markets take off or tank. Therefore, the trading is always disadvantageous and results in handing out values for free, i.e. below market value. Even if you are managing a gigantic portfolio and your trader's losses are small compared, you would try to limit this kind of trading (or suggest another job...)
