### ISSUE TITLE
Spinner sometimes stalls when trying to complete a payment request

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#5856]
### Expected Behavior
Payment requests are fulfilled when "send" is pressed.

### Current Behavior
Sometimes, but not the majority of times, the spinner that appears when a user presses the "send" button on a payment request notification just keeps spinning forever.

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine I have verified this issue useing latest Android internal build v1.5.5(1004294323) and Test Flight build v1.5.5(34) & observed that issue is not reproduced.
**Does not repro on devices:** Samsung Galaxy A5(7.0), iPhone SE (13.5.1)
Attachment:  [SpineerIsNotDisplaying.mp4](https://drive.google.com/file/d/1JXSZrxMguz57738XQrLY9xcA8-Rx2d2y/view?usp=sharing)
