### ISSUE TITLE
More robust test environment

### ISSUE THREAD

**Issue by carterqw2** [celo-org/celo-monorepo#6024]
**Acceptance Criteria**

- [ ] There are end-to-end tests.

**Comment by eruizgar91** [comment]
I have been working on this issue for a while but I have been not able to finish due to some blockers. Mainly because some of the APIs that we are calling when we use contractkit are not implemented in ganache. My current work is in this branch https://github.com/celo-org/komenci/tree/eruizgar91/adding-e2e-tests .
The methods of the tx API, as txpool_content are not in ganache and will need a workaround to make it possible to test the e2e.
