### ISSUE TITLE
Monitoring of the metadata-crawler (which monitors attestation services) -> Web Services

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#6064]

**Comment by aslawson** [comment]
@timmoreton where you just thinking of alerts if the service was down? any other specific metrics?

**Comment by carterqw2** [comment]
From Tim:

What’s needed is just to make sure the cron job completes successfully when it’s expected to.
We’ve seen issues where the blockscout deployment switches between 1 and 2 and the metadata crawler doesn’t run (or is out of date).
It’s also possible there’s an error in the actual running of the cron job, but I don’t think we’ve seen that. (One known issue is that the severity field isn’t getting interpreted correctly..going to be a fluentd - stackdriver thing)

The crawler does two things:
* adds domain name claims to blockscout
* goes over attestation service claims, and for each checks status/liveness, and writes that to log (which then gets picked up by DBT/metabase pipeline) and also POSTs to a webhook to show attestation service problem messages in #mainnet-alerts on Discord
the monitoring is needed to make sure all of these different things keep happening… each has kind of different consequences if it doesn’t happen.

**Comment by yourbuddyconner** [comment]
Ok did some investigation into this and I believe this is the gameplan: 

Since `metadata-crawler` is a Kubernetes Cronjob, we can monitor it via the new `kube-state-metrics -> Prometheus -> AlertManager` Alerting pipeline. 

Good context on the task can be found here: https://medium.com/@tristan_96324/prometheus-k8s-cronjob-alerts-94bee7b90511

Tasks are as follows: 
- Ensure `kube-state-metrics` is enabled on all the important clusters. 
- Enable forwarding of  prometheus metrics for those clusters to Grafana Cloud
- Write alerts that capture the failure conditions we're watching for (ex. Failed Job)
- Push alert config to AlertManager in Grafana Cloud


Additionally, we could also use this as a pilot for log-based alerts using Loki/Grafana Cloud as follows: 
- Install Loki as a DaemonSet on all clusters containing instances of Metadata-Crawler
- Write alerts that capture the errors/failure conditions we're watching for (ex. Error in Logs)
- Push alert config to AlertManager in Grafana Cloud 

This task would be blocked pending Phase Zero of the Metrics Cost Reduction Project as detailed in #6587

**Comment by carterqw2** [comment]
Sounds good!

**Comment by joe-bowman** [comment]
Would it be possible for operators to register an alert email address / discord / phone number that can be alerted in these situations?

(it doesn't negate the need for operators to run their own monitoring, but sometimes additional monitoring is very useful!)
