### ISSUE TITLE
[P0] Improve our debugging capabilities

### ISSUE THREAD

**Issue by i1skn** [celo-org/celo-monorepo#6105]
# What's important about this?
- Impacted users is a bit incorrect, we should try to use the user address maybe?
- Sentry report missing breadcrumbs with redux actions
- Uploaded logs uses client provided time (folders in the future)
- No easy way to access full logs from sentry report
- Stack traces can't be reconstructed in some cases
# What is "done"?
* Make alerts actionable.
* Improving debugging compatibilities in Sentry.
# What's involved in doing this work?
* Include logcat logs to Sentry and when user contact support.
* Fix stack traces.
* Fastlane uploads the symbols for native libraries.
# Open questions:
* How best to reproduce a bug, which someone else is having?
* Geth logs are captured in sentry

**Comment by etuleu** [comment]
Impacted users was affected by a sentry bug which is now fixed by updating to the latest versions of their libraries.
I also enabled the new grouping feature that they have which tries to group with a better regex that ignores specific memory addresses and line numbers. This combined with the user ids fix should help grouping.
