### ISSUE TITLE
Break up Utils Package

### ISSUE THREAD

**Issue by barbaraliau** [celo-org/celo-monorepo#6189]
https://bundlephobia.com/result?p=@celo/utils@1.0.2

- biggest impact will be cutting from the phonenumber and bip libs

**Comment by aaronmgdr** [comment]
What sort of approach are we thinking here?

I think a breaking change would be good: create a new @celo/phone-utils for the stuff that uses google-lbphonenumber and remove those functions from @celo/utils package

**Comment by aaronmgdr** [comment]
# approaches for the phonenumber parts

Been thinking about this a bit. here are my thoughts. 

## New Package  (remove phoneNumbers.ts file from utils and place in new `phone-utils` package)

### pros 
* simplest change from implementation perspective
* simple change from use perspective (just add an import and change references)

### cons
* google lib phone means this new package will still be hundreds of kb


### opinion 
 feels like the least disruptive way

## Dependency Injection -- rewrite so that google-libphonenumber is an optional peer dep 

### pros 
* each downstream user can handle their own google-libphonnumber
* potentially can inject a wrapped version of something else instead of google-libphonenumber

### cons 
* huge change in how its used (very breaking in its changes)

### opinion 
* potentially over complexifies.

## Replace google-libphonenumber with [libphonenumber-js]( https://www.npmjs.com/package/libphonenumber-js)

### pros 
* smaller size 145 kB vs 550KB

### cons
* different api 
* still over 100kb
*  doesn't support formatting non-"conventional" numbers like numbers with the "area code" omitted

### opinion
Given how many people will want to use the utils but not need phonenumbers stuff this option alone is insufficient for our size goals. However this could be a supplemental option down the road. 

## Conclusion

All of these are breaking changes and so will require a major version bump to 2.0

My thought is that best bet is option one due to its simplicity.

**Comment by jmrossy** [comment]
I vote for option 1 for now. We could still swap to libphonenumber later (option 3) if we need but I bet that will introduce a bunch of subtle issues in some countries.

**Comment by jeanregisser** [comment]
Option 1 sounds good to me. 

We've wanted to update `google-libphonenumber` and potentially replace it with `libphonenumber-js` for a while too.
But this can happen independently.

**Comment by aaronmgdr** [comment]
Plan

Release a new celo/phone-utils package 
release version 2 of contract Kit without the google libphone
