### ISSUE TITLE
Spinner does not reset when user presses back from SendConfirmation screen

### ISSUE THREAD

**Issue by tarikbellamine** [celo-org/celo-monorepo#6308]
### Expected Behavior
When a user hits the back button on the SendConfirmation screen, it cancels the transaction and resets the loading spinner.

### Current Behavior
Loading spinner does not refresh unless transaction is completed, failed, or app is refreshed.

**Comment by tarikbellamine** [comment]
After digging into it, I believe this has been addressed by #6002

**Comment by Lss-Ankit** [comment]
Hi @tarikbellamine  Verified issue using Android  internal build V1.7.2(1004294329) &Test Flight build V1.7.2(39) and found that issue is fixed. 

- Verify "The PIN is necessary. pls try again" message is shown when user taps on < arrow from Enter PIN screen after proceeding for payment once completing secure send flow.

Steps: 
1. Make sure user is logged in. 
2. Tap on Send button. 
3. Tap on Search fields and search the number who has two account with one number. 
4. Enter an amount and tap on review button. 
5. Tap on Confirm Account number. 
6. Enter 4 digit account number of user B. 
7. Tap on Submit button. 
8. Tap on Send button. 
9. Tap on < from Enter PIn screen. 
10. Observed "The PIN is necessary. pls try again" message is shown 

Please let us know if you have different repro steps for the same.
