### ISSUE TITLE
Improve UI for disabled radio buttons (CICO)

### ISSUE THREAD

**Issue by dominiquejane** [celo-org/celo-monorepo#6328]
### Expected Behavior
User SBAT immediately differentiate between unavailable and available options

### Current Behavior
When choosing a cash-in provider/option the disabled buttons (for the top radio row) may appear as if they are simply not selected (when they are actually disabled).

**Comment by michellewong793** [comment]
addressed by the new designs for the radio button? #6501

**Comment by calrobertlee** [comment]
@michellewong793 it seems that part of the design didn't make it into the code.

**Current behavior (for disabled radio item):** 

- radio button's stroke color remains at `gray 3` (which is the same color as unselected)
- text color changes to `gray 3`

**Expected behavior (for disabled radio item):** 

- radio button's stroke color changes to `gray 2`
- text color changes to `gray 3`

Let me know if you have any other questions!

**Comment by michellewong793** [comment]
closed with #6501
