### ISSUE TITLE
Update celotool to allow upgrading of all deployed Prometheus Instances

### ISSUE THREAD

**Issue by yourbuddyconner** [celo-org/celo-monorepo#6596]
Update celotool to allow upgrading of all deployed Prometheus Instances. 

Currently certain K8s clusters are deployed using slightly different tooling within the `celotool` codebase. Details from my DMs with @tkporter: 

> there are 2 ways that we specify a cluster for a particular env:
> 
> 1. via contexts, where there can be more than 1 context per environment. They're specified like this: https://github.com/celo-org/celo-monorepo/blob/master/.env.rc1#L79, and in that example you'd use a celotool command with that env/context by using --celoEnv rc1 --context azure-oracle-westus
> 2. via "top level" env vars like this: https://github.com/celo-org/celo-monorepo/blob/master/.env.rc1#L10, where there is only 1 set of env vars that specify the cluster in a single env file.
> 
> Contexts are the "newer" version now that we have to deal with many clusters per environment, and are the way that we manage oracles, komenci, and forno. Method 2 is the old way
> 
> The link you shared only works for clusters specified in the method 2 way, as it reads those top level env vars in the call switchToClusterFromEnv. You'll also need to support method #1 by creating a command that takes in the context and switches to the appropriate cluster, like how this command does it: https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/cmds/deploy/upgrade/oracle.ts#L24 (edited) 
> 
> I usually think of the cluster that's specified with method 2 as like the "main cluster" for the environment-- eg for mainnet/rc1, the cluster is the one with blockscout, celostats, etc
> 
> And then the "context" clusters are like auxiliary clusters with specific purposes 
> 
> -> Ok my next question is how did prometheus on the "context" clusters get installed initially?
> 
> This call I shared earlier https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/cmds/deploy/upgrade/oracle.ts#L24
> will read the appropriate env vars for the specific context, and then it'll use those values to create a "ClusterManager", of which we have different implementations for each cloud-platform here: https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/lib/k8s-cluster. It'll then attempt to switch kubectl to use the appropriate kube context (or download the kube context credentials if they don't exist yet) in this function: https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/lib/k8s-cluster/base.ts#L25
> 
> After switching the kube context, that function will also perform any setup it needs to for the cluster with a call to setupCluster. The base implementation for that is here: https://github.com/celo-org/celo-monorepo/blob/master/packages/celotool/src/lib/k8s-cluster/base.ts#L67, but the cloud platform subclasses may have additional stuff too. But what matters is the installAndEnableMetricsDeps call, which will install the prom helm chart

**Comment by jcortejoso** [comment]
Currently celotool can deploy prometheus using helm only in GKE clusters. For that there is a `gke-prometheus` which can manage the lifecycle of the helm release (install, upgrade, destroy).
The goal of the issue is replacing the command by a generic `prometheus` celotool command that can manage the lifecycle of the prometheus releases based on cluster contexts or the "top level" cluster. I consider we can include the `kube-state-metrics` lifecycle together with prometheus.

Also the issue could be a good opportunity to review the "default" packages we deploy with a cluster. For example, it could be interesting decouple the `nginx-ingress` and `cert-manager` deployment from the gke cluster lifecycle (currently deployed in a function called `setupCluster`, that only runs on gke) and create a new command, similar to `prometheus` that can help with the lifecycle of nginx and certmanager.
