### ISSUE TITLE
Verification should not assume libraries are reused across core contracts

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6606]
### Expected Behavior

Tooling should check for all

### Current Behavior

The verification tooling assumes that libraries are reused across core contracts, which won't be the case if a subset get upgraded later

**Comment by yorhodes** [comment]
Closing in favor of https://github.com/celo-org/celo-monorepo/issues/6080
We want to maintain the invariant that a library upgrade implies an upgrade in all of the downstream contracts

**Comment by yorhodes** [comment]
It *seems* like we are encountering this issue when a change is made to a linking contract. 

See https://app.circleci.com/pipelines/github/celo-org/celo-monorepo/34134/workflows/d43c205a-82c6-4892-b3f2-5d9fd63fc371/jobs/438913/parallel-runs/0/steps/0-104

`Accounts` has been changed, implying a new `Signatures` deployment and linkage (because we don't maintain a history of deployed libraries).

Other linking contracts (in this case `GoldToken`) are linking an old `Signatures` deployment. The library bytecode hasn't changed but the deployed addresses are different.

Thus `verify-bytecode` fails [when collecting addresses on `GoldToken`](https://github.com/celo-org/celo-monorepo/blob/02ac2bafd8ce4b14cc40ed1c37f246582785f4fa/packages/protocol/lib/compatibility/verify-bytecode.ts#L131) with [mismatched addresses](https://github.com/celo-org/celo-monorepo/blob/7f9b0bef8dcf752ff9684625067189cb3bb22f3f/packages/protocol/lib/bytecode.ts#L123).

cc @m-chrzan
