### ISSUE TITLE
Verify current release without requiring checkout of current release tag

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#6615]
### Expected Behavior

`master` works for verifying current release

### Current Behavior

new contract identifiers (ie `StableTokenEUR`) cause verification to fail on master

**Comment by nambrot** [comment]
So the question is what the solution should look like. The point of this step is to assert that the network is in the state we expect it to, i.e. working. However, what is working mean and what should be the source of truth? I.e. if a new contract gets added, should the list in source code or the registry be the source of truth?

I think the source code should be considered the source of truth as it is the one that is audited. Prior releases could have gone wrong and not registered a contract in which case the environment should be considered at least possibly faulty.

Hence, the tooling/developers should explicitly acknowledge to a user that a new contract was added, and thus will not be reflected. I.e. the list in the tooling should really have a notion of when it was added.

However, since there is no notion of "releases" at the code-level, it does seem that the only way this can be done is to check-out the old constant, and use that as the source of truth indeed.

**Comment by yorhodes** [comment]
@alecps and I ran into the same issue during the `verify-release` step of deploying release 2
cc @nambrot

**Comment by nambrot** [comment]
Alright, I have to reopen this issue again, because the Fix of #6850 and #6899 did not actually work after you consider https://github.com/celo-org/celo-monorepo/pull/6780. Specifically we have two competing desires:

1) For the purposes of verifying in `verify-deployed` we need some source of truth of which contracts need to be checked. The `CeloContractName` enum in `registry-utils` was thought of the best.
2) Migrations and tests may be updated to refer to newly added contracts in the `CeloContractName`

It is clear that we can't just pick one or the other, and we need a more fundamental change to the tooling to reflect this change.

**Comment by nambrot** [comment]
I'm inclined to even give this a P1

**Comment by yorhodes** [comment]
https://github.com/celo-org/celo-monorepo/pull/7309 gave us most of what we want here (checking out only old contracts directory but using canonical tooling)
unfortunately the git version in our circleCI image doesn't support `git checkout --no-overlay` so new contracts from newer tags aren't removed from the tree when checking out older tags, causing the contracts to appear errantly in both releases
