### ISSUE TITLE
Complete ContractWrapper for Exchange

### ISSUE THREAD

**Issue by mcortesi** [celo-org/celo-monorepo#675]
### Expected Behavior

Complete ContractWrapper for Exchange

**Comment by mcortesi** [comment]
@m-chrzan can you describe what solidity methods should we port.. and or any particular interface you see fit

**Comment by m-chrzan** [comment]
Definitely want:

    exchange
    getBuyTokenAmount
    getSellTokenAmount
    getBuyAndSellBuckets

One thing to consider is whether we want to expose these as they are in the contract, with a `sellGold` flag passed in, or each in two versions, like `sellGold()` and `sellDollar()` instead of `exchange()`.

Whether we want to expose `onlyOwner` functions is an open question - it could potentially be useful for people playing around with a local network? But other than that, they pollute the namespace.
