### ISSUE TITLE
ASv1 integration docs 

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#6753]
External developers and integrating partners should be able to access and create phone number mappings. 

Other developers currently can read Valora created mappings by calling ODIS (for the pepper) and making the onchain request, but it is unclear on how to do so. Creating mappings is complex and there are no clear standards on how to do so.

Create documentation on how to access phone number mappings (via ODIS + onchain requests)
Create documentation on how to create phone number mappings

**Comment by codyborn** [comment]
This was just created as a [potential Gitcoin bounty](https://www.notion.so/clabsco/Write-a-tutorial-for-interacting-with-on-chain-phone-number-mappings-b9dde59c185d4ef2a592e549100343a1).

**Comment by alecps** [comment]
ODIS pepper querying docs can be found here: https://docs.celo.org/developer-guide/contractkit/odis

**Comment by alecps** [comment]
This ticket should be investigated alongside the Kaala integration

**Comment by alecps** [comment]
Add documentation for the following inquiry from Slack:

Q: "I have a quick question about the twilio verify integration. In my validator twilio logs, I see a bunch of expired entries. Is this expected? Does the attestation server tell twilio that someone successfully entered the code?"

A: "Yeah this is expected; we currently don’t have the additional call to twilio to check that the verification is correct, since we already manage this logic within the attestation service." 

Related Discord thread: https://discord.com/channels/600834479145353243/654086275900375041/876811949550206987
