### ISSUE TITLE
Developers should be able to quickly initialize dev blockchain with core contracts

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#6758]
### Expected Behavior

It should be easy and obvious to have a dev blockchain with core contracts

### Current Behavior

Developers have to know how to run ganache and the migrations to get the core contracts in a state to develop or test against

Developers can also use the devchain right now which isn't as obvious though.

**Comment by nambrot** [comment]
From @mcortesi 

```
Ok, i have a working version… missing one or two migrations, but it’s good enough to check it out.
I need beta testers…
Checkout mc/magic branch, and then
make all
alias mycelo=$PWD/build/bin/mycelo
mycelo # just to see subcommand options
mycelo create-config myenv
# check ./myenv/config.json and modify if needed
mycelo create-contracts-config myenv
# check ./myenv/contracts-config.json and modify if needed
# Make sure your contracts are built already (they always are anyway)
mycelo create-genesis myenv --buildpath $CELO_MONOREPO/packages/protocol/build/contracts
# You'll find ./myenv/genesis.json with all migrations already in it
# You can now use that file to run your own geth instances
# but if you're up for more wonder you can also run the tesnet
# Creates datadir and run geth init, imports account, set static nodes files
mycelo init-nodes --geth ./build/bin/geth myenv
# Run the tesnet
mycelo run --geth ./build/bin/geth myenv
# If you want to check the logs, do `tail -f myenv/validator-01/geth.log`
Looking for some initial feedback!!
Some details about config files:
config.json contains basic information about the chain (chainId, istanbul parameters, mnemonic, nro of validators)
contracts-config.json is the replacemente of migrationsConfig.json. It’s quite similar. Right now it requires the config.json since it uses the accounts dervied from that file for some default config
genesis.json the usual file for geth init but in this case, Alloc is fully populated with all smart contracts and their state after running the migrations. It uses information from previous config files to run
```

**Comment by aslawson** [comment]
@nambrot it looks like we have `yarn test:livechain` which will deploy a local development chain with core contracts. is this ticket suggesting something different or more?

https://docs.celo.org/developer-guide/development-chain#download-the-celo-monorepo

**Comment by nambrot** [comment]
Huh, didn't know we had this page. I would probably still keep this ticket open since the linked solution isn't very user friendly. For example, it's unclear what accounts can be used.

**Comment by mcortesi** [comment]
You can already use `mycelo` for this. check https://github.com/celo-org/celo-blockchain/blob/68e2ab747b40ce215a916cde7fdc77613366dcd0/cmd/mycelo/README.md

**Comment by aslawson** [comment]
@mcortesi comparison with the existing options for devchains

`test:livechain`:

- Relies on devchain.ts within the monorepo
- devchain.ts. Runs a ganache instance, then runs migrations on top. Saves the chain state on a .tgz you can later use to launch your own ganache instance
- When you want to run a ganache instance, you need a copy of this chainstate.tgz and use it for your own ganache instance

PROs:

- Run ganache, which is easier for most.

CONs:

- Ganache is not 100% compatible with celo-blockchain. You can’t do thinks like paying gas with cUSD, nor use any of the precompiled smartcontracts. I’d doubt it will ever be 100% compatible.
- You either need access to a already generated chainstate.tgz or you need to generated yourself. This implies having the whole monorepo, compile the contracts, etc.
- Takes time to generate a chainstate.tgz, since you need to run migrations

`mycelo`

- It’s a binary, no need to download the repo.
- You do need access to the truffle compile outout (the  *.json on protocol/build/contracts)
- Also need access to a geth binary
- mycelo generates a genesis.json, with all migrations already in it. That takes only a second to generate.
- You can use the genesis.json as you want. You could use it to deploy a k8s cluster, run a local node, etc.
- mycelo provides also commands to run your own local tesnet with 1 or many validators
- mycelo provides a command to generate load into a node and will eventually support other commands, and other configs

PROs:

- Really fast to “run migrations”. Much cleaner. This is great if you’re actually working with core contracts and you need to change migrations config, contracts and then run migrations again
- You get ALL the features. since you’re actually running a geth instance, not a copy of it

CONs:

- Not ganache. Doesn’t have snapshot and rollback commands, that you use for unit tests in ganache.
- You need truffle compile output to run it

**Comment by aslawson** [comment]
There is some remaining work for making either option truly easy-to-use for external devs

Either: 

- uploading a chainstate.tgz & release a binary or script that run ganache using that state.

AND/OR

- uploading the truffle artifacts everytime we do a contract release, so when you run mycelo you just download those
- Release mycelo as a binary, have a simple way to install it. (this should be really simple, it’s already a binary, we just need to create a homebrew version of it, or something like that)

We do have a grant recipient working on ganache compatibility. @critesjosh do you know if that includes scripts to run local ganache instance with existing chain states?

**Comment by mcortesi** [comment]
just to add to this....

i would take a look at ubeswap repositories. They are using hardhat for everything, and that seems to be the ideal option. Of course, that means you need hardhat to support celo's protocol

**Comment by yorhodes** [comment]
potentially a good intern project h/t @kevjue

**Comment by kevjue** [comment]
We should do some investigation here on the correct solution.  E.g. do some product work, such as determining who are the stakeholders.

**Comment by nambrot** [comment]
We'd recommend for this ticket scope to :
- Find a way to publish the devchain archive for folks to use
- Document how to use it with truffle + hardhat

**Comment by yorhodes** [comment]
this is to document existing process and usage
note distinction from https://github.com/celo-org/celo-monorepo/issues/8208

**Comment by yorhodes** [comment]
link to celo-devchain
update with release4
