### ISSUE TITLE
“Learn More” alignment not fit to screen on CELO Rewards Program page from Earn Rewards pills.

### ISSUE THREAD

**Issue by Lss-Ankit** [celo-org/celo-monorepo#6936]
**Frequency:** 100%
**Repro on build version:** Android Internal Build V1.9.2(1004294334)
**Does not repro version** Test Flight Build V1.9.2(44)
**Repro on devices:** Samsung Galaxy A5(7.0),Samsung Galaxy J5 Prime (8.0)
**Does not repro devices** Samsung Galaxy A21s(10.0), iPhone 8(14.2)
**Testing Account:**  272 381 9637 / [Backup Key](https://docs.google.com/spreadsheets/d/1Iy41GGA6e2pES2XHjBn7nb8X3n8zZsu7EW1jvwD2e70/edit#gid=0&range=B22)
 **Repro Steps:**
1. Launch the application and login with a test account.
2. Tap on Hamburger Menu.
3. Tap on “Earn Rewards” pills.
4. Now the user should be on the “CELO Rewards Program” screen.
5. Observed that,
**Current Behavior:**  “Learn More” button alignment does not fit to screen.
**Expected Behavior:**  Alignment should be proper.
**Impact:** Bad user experience.
**Attachment:**  [LearnMoreButtonNotFitToScreen.mp4](https://drive.google.com/file/d/1wKxSpyRXMk79FKN_uT9SCZ-d8---fvBX/view?usp=sharing)

**Comment by ValoraQA** [comment]
Hi  I have verified this issue using latest Android Internal Build V1.11.1(1004294339) & observed that issue is fixed now.
**Verified on Devices:** Samsung Galaxy A5(7.0), Samsung Galaxy J5 Prime (8.0)
**Attachment:** [LearnMoreAllignment.mp4](https://drive.google.com/file/d/1FT2w0NEmYLJ0N5y2CzSBT85tnXyNbPA8/view?usp=sharing)
