### ISSUE TITLE
Metabase occasionally returns 503 error

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7011]
Based on the metabase logs, it seems that the server crashes and restarts a couple times each day. While it's booting up, the server responds with 503, making the dashboards inaccessible.

https://metabase.celo-networks-dev.org/admin/troubleshooting/logs

During this time, there are also large fluctuations in memory and CPU:
https://console.cloud.google.com/kubernetes/deployment/us-west1-a/celo-networks-dev/metabase/metabase2/overview?project=celo-testnet&pageState=(%22deployment_overview_active_revisions_table%22:(%22r%22:50))
![image.png](https://images.zenhubusercontent.com/5f8782182bc44530856af91b/a5e3e394-3b6b-4d8f-950e-071f17f5a98d)

**Comment by yourbuddyconner** [comment]
Did some investigation on this previously. This is due to the Postgres database (k8s statefulset) restarting, and failing to serve SQL queries from Metabase, manifesting in 503s on the frontend. 

When I looked at this, my hypothesis was that some query was causing Postgres to panic and restart, but wasn't able to exhaustively drill down into all the jobs Metabase was running at the time.
