### ISSUE TITLE
Missing or lost funds

### ISSUE THREAD

**Issue by sned1966** [celo-org/celo-monorepo#7068]
*Describe your issue here.*

### Environment
* Elixir Version: 1.9.0
* Erlang Version: 22
* BlockScout Version: d09fdbfd87d54ba1a80de57ea48c5c7e6f4f61f8

* User Agent: `Mozilla/5.0 (Linux; Android 8.0.0; SM-G955F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.152 Mobile Safari/537.36`

### Steps to reproduce

*Tell us how to reproduce this issue. If possible, push up a branch to your fork with a regression test we can run to reproduce locally.*

### Expected Behaviour

*Tell us what should happen.*

### Actual Behaviour

*Tell us what happens instead.*

**Comment by medhakothari** [comment]
Hi @sned1966! Could you give us more information here? For example, what network was this on (e.g. mainnet, alfajores)? Where were you sending the transaction from? Were you sending cUSD or CELO? Can you confirm that the funds left from the first address? Any more information here would be super helpful!

**Comment by sned1966** [comment]
https://explorer.celo.org/tx/0xf6ec9039cb39b43a06283eff94f37c3434bb646566c518064ca30510111af833/token_transfers
this is wa hat coin base sent me to show where the money went I sent from
coin base to my Cleo wallet witch I thought was my coin base wallet but
it's not there if you could help me please

**Comment by sned1966** [comment]
Sid that help or is there anything else I can do to recover this money

**Comment by sned1966** [comment]
I have sent the info over a week ago it would be nice to get some sort of
reply

**Comment by medhakothari** [comment]
Whoops sorry about that! accidentally deleted a comment instead of replying. So it looks like the transaction successfully left your coinbase account. Can you confirm that the funds have left that wallet? Also can you confirm that your Celo wallet address is `0xf21490Fb30A5ea8af5aC766dD53088B9aC0877FD` (got it from the explorer link you sent)

**Comment by sned1966** [comment]
Yes that's what coin base told me

**Comment by sned1966** [comment]
Any update on my funds being returned to my coinbase acc yet

**Comment by sned1966** [comment]
Have you deleted my email again

**Comment by sned1966** [comment]
Once again I'm left waiting on a reply from you I'm starting to get really
pissed of I gave you the info you require and I feel I have been robbed

**Comment by medhakothari** [comment]
Hi -- apologies. When you say "Celo Wallet", do you mean Valora? and if so, can you confirm that at the bottom left of the Valora App, your address is `0xf21490Fb30A5ea8af5aC766dD53088B9aC0877FD`? if not, I would suggest you also start a ticket with [coinbase support](https://help.coinbase.com/en/coinbase/getting-started/other/how-can-i-contact-coinbase-support). The issue is that your funds aren't necessarily lost, as the address above does contain them, which you can verify [here](https://explorer.celo.org/address/0xf21490fb30a5ea8af5ac766dd53088b9ac0877fd/transactions). The issue is that I'm not sure whether you have access to that address or not (do you hold the private keys for that address?). I'm still trying to understand where you got that address from. Unfortunately if you don't hold the keys to that address, there is no way to get those funds returned. 

Also, apologies for the delay here -- didn't get any notifications for them. I empathize with your situation, and I'll try my best to help you out!

**Comment by sned1966** [comment]
Coinbase told me you hold the keys when I sent them to my wallet in the box
was my email witch it said it recommends I I hit send and this is where we
are at now this wallet you said how do I get into that do I need to
download it to I though the only wallet I needed was a coinbase one

**Comment by sned1966** [comment]
I just got that wallet that you said and I never did any of that Be for was
not asked to do that when I sent them from coin base as I though I was
sending to coinbase wallet now if you could use the keys that coinbase say
you have to my funds I'm sure this will get sorted fast

**Comment by medhakothari** [comment]
If you hadn't downloaded/used Valora before, then no worries, that shouldn't be needed now. Unfortunately we don't hold any keys; I think you should chat with Coinbase's customer service as they will better be able to serve this specific request, since it seems like they're the ones who pointed you to the `0xf21490Fb30A5ea8af5aC766dD53088B9aC0877FD` address

**Comment by sned1966** [comment]
I'm still waiting to find out what can be done over my missing money you
say it's down to coinbase they say it's down to yourselves and all the time
I'm out of pocket

**Comment by sned1966** [comment]
Are you going to tell me again you did not get notice of my email again I'm
being sent to yours from coinbase your sending me to coinbase and I'm the
one that is missing funds I need this sorted

**Comment by dominiquejane** [comment]
@sned1966 Hi I was looking over this conversation and wanted to see if I could help in any way.
You said you sent funds from coinbase to another wallet, correct?
Do you have access to this wallet? If you don't have access to this wallet then how did you acquire the address for the wallet?

**Comment by sned1966** [comment]
When I sent them it showed my email address in the little box as I did not
really understand I just hit send I have spoken to coin base they say you
hold the keys so I should ask you for this you have told me they are the
ones to refund me I told them this and they just closed the case

**Comment by dominiquejane** [comment]
Could you replicate what you did and attach screenshots of your process? Just don't actually go through with any transaction. 
Also, I think the coinbase support agent may not be aware of how cLabs works because we don't hold the private keys for any user. Coinbase, on the otherhand, does control the private keys for its users, so I can see why they may have sent you a confusing message.

**Comment by sned1966** [comment]
I just tried it won't let me take a screenshot of the transaction but you
can see from my acc that it's sitting there I can send this one it's the
one that says sent Cleo to Cleo wallet _177 and as for coinbase they just
keep telling me to ask you for the money back

**Comment by dominiquejane** [comment]
@sned1966 
Can you send me a link to download the same wallet you used? This will give me more context.

**Comment by sned1966** [comment]
Is this what you are looking for?

**Comment by dominiquejane** [comment]
The link is missing

**Comment by sned1966** [comment]
Any luck with my funds

**Comment by dominiquejane** [comment]
@sned1966 You forgot to paste the link in your last message.

**Comment by sned1966** [comment]
https://explorer.celo.org/tx/0xf6ec9039cb39b43a06283eff94f37c3434bb646566c518064ca30510111af833/token_transfers

**Comment by sned1966** [comment]
Is that what you needed

**Comment by dominiquejane** [comment]
No, I need to know which wallet you tried to send your funds to. 
In an earlier comment you said something about a Cleo wallet?
I need to know about your wallet so I know how your address was generated. If I have that information then I will know if it's possible to recover your funds.
So did you get your wallet from the app/play store? From a website?

**Comment by sned1966** [comment]
I tried to send it to my coin base wallet I got that from coin base website
do you need my wallet address?

**Comment by sned1966** [comment]
Is this any good

**Comment by dominiquejane** [comment]
Ah... this sounds like a similar situation I just ran into.
Can you check out this other issue and see if you're in the same situation?
If you are, then you can follow the steps I listed.

https://github.com/celo-org/celo-monorepo/issues/6353

**Comment by sned1966** [comment]
Thank you very much all is ok now I got all my funds back with your help

**Comment by dominiquejane** [comment]
That's great! I'll close this issue now. Have a great day!
