### ISSUE TITLE
Upgrade Monorepo dependencies to support Node > v10 LTS 

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7084]
The maintenance on v10 ends in April 2021. https://nodejs.org/en/about/releases/.

**Comment by aslawson** [comment]
Will still work with old versions but cannot get new changes (including security patches)

**Comment by AlexBHarley** [comment]
As noted in the DevEx sprint planning.

- should this include updating our services to run on Node 14 or 16?
- should this include updating Valora (really the whole wallet package) to run on Node 14 or 16?

**Comment by piersy** [comment]
So I've used my 2 dev days for this sprint.  I've made some progress on this see [here](https://github.com/celo-org/celo-monorepo/pull/7424). Running `yarn` and `yarn build --ignore docs` works with node 12. But CI fails because the e2e tests rely on published modules which still restrict node to version 10. The next step is to ensure all of CI passes, possibly by publishing all the modules that have been updated as dev packages, or potentially there is some other better way.

**Comment by piersy** [comment]
So this now seems to be working for node 12.

Node 14 poses a probelm because the current version of ganache-core that we use (which is our own version distinct from truffle's) does not support node 14. A lot of CI jobs fail with the following error.

```
Error: Callback was already called.
    at /home/circleci/app/packages/protocol/node_modules/@celo/ganache-cli/build/ganache-core.node.cli.js:17:276
    at s.<anonymous> (/home/circleci/app/packages/protocol/node_modules/@celo/ganache-cli/build/ganache-core.node.cli.js:17:2238)
    at s.emit (events.js:315:20)
    at s.EventEmitter.emit (domain.js:467:12)
    at s.destroy (/home/circleci/app/packages/protocol/node_modules/@celo/ganache-cli/build/ganache-core.node.cli.js:46:747880)
    at finish (internal/streams/writable.js:670:14)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
```
This was resolved several months ago in truffle's ganache-core see - https://github.com/trufflesuite/ganache-core/issues/568, but it's not clear what the actual fix was since the release that fixed it contained a lot of changes. The celo version of ganache-core is not an actual fork on github, but looking through the history it looks like the project was forked at v2.10.2 and the diff between that and the fixed ganache core is 12K LOC and on top of that our version of ganache core has a few hundred lines of our changes.

So in order to progress to using node 14 we need to either upgrade our ganache-core or use something else entirely (if that is even possible).

There doesn't appear to be any documentation that explains what are the changes we made to this repo, so as a starting point we could get in touch with the authors (from clabs), listed here in order of number of commits. 

      1 Jean Regisser
      1 Mariano Cortesi
      1 Nam Chu Hoai
      1 Piers Powlesland
      2 Yorke Rhodes
      4 Asa Oines
      4 dependabot[bot]
     10 Sami Mäkelä

**Comment by aslawson** [comment]
@piersy RE: ganache changes to support v14 --
https://github.com/trufflesuite/ganache-cli/releases/tag/v6.12.0

^ looks like relevant updates are: https://github.com/trufflesuite/ganache-core/pull/636 and https://github.com/trufflesuite/ganache-core/commit/c26ba24ebf24d1c09b328a76baf0cf43e82fba04

**Comment by piersy** [comment]
I discovered there is a problem with the caching of node_modules in CI, this still needs to be fixed.

**Comment by barbaraliau** [comment]
update: first part of upgrading to node 12 has been merged. need to release the affected packages and then can proceed with updating CI to use node 12
