### ISSUE TITLE
Implement Crowdin translation management tool

### ISSUE THREAD

**Issue by ole-nov** [celo-org/celo-monorepo#7130]
- [ ] Add Crowdin SDK to Valora App;

- [ ] Import translation keys.

**Comment by comradekingu** [comment]
How does Crowdin fit into

>we are aiming to create a new platform to connect people globally and bring financial stability to those who need it most.

?

**Comment by ole-nov** [comment]
Implemented

**Comment by comradekingu** [comment]
@aleksey-nov 
Crowdin doesn't have a community, and it specifically is only gratis for non-commercial projects.
For anything else, it is subject to their enterprise plans, and surveillance commercialization.
There is no option to avoid any of that, since it is closed source software, as-a-service-only.
And at that, only for people 18 and above.
