### ISSUE TITLE
Exchange.sol should not expect SortedOracle reports

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7171]
### Expected Behavior

Exchange contract does not require

### Current Behavior

Exchange requires

**Comment by yorhodes** [comment]
Zeroes were used for the stable token address in `ExchangeEUR`'s [statically defined initialization parameters](https://github.com/celo-org/celo-monorepo/pull/6933) because the to-be-released `StableTokenEUR`'s address is not known at compile time. 
The [`_updateBucketsIfNecessary()` call](https://github.com/celo-org/celo-monorepo/blob/a675fd719f7fe5ddd676affd69b263f21508b85f/packages/protocol/contracts/stability/Exchange.sol#L97) at the bottom of `Exchange.initialize` was reverting when looking up [whether `SortedOracles` exchange rate reports were expired on a `stable` token address](https://github.com/celo-org/celo-monorepo/blob/a675fd719f7fe5ddd676affd69b263f21508b85f/packages/protocol/contracts/stability/Exchange.sol#L414) defined as  zeroes.

**Comment by yorhodes** [comment]
The workaround used for contract release 3 was to manually modify (see #7233) the `stable` token address in the governance upgrade proposal to reflect the deployed address, allowing the `_updateBucketsIfNecessary()` call to return without reverting.
My recommended solution is to use a registry identifier akin to the [inverse relationship that `StableToken` uses](https://github.com/celo-org/celo-monorepo/blob/16d35bc40fbd49a96f1f6ee811d9e6daa2ecb31c/packages/protocol/contracts/stability/StableToken.sol#L119) to refer to the corresponding `Exchange` contract in Mento, and to remove the `_updateBucketsIfNecessary()` call from the `initialize` function.
Care should be taken to ensure backwards storage compatibility with the `stable` token address that is currently used in `Exchange`.

**Comment by yorhodes** [comment]
@Tjudice good candidate
