### ISSUE TITLE
Create minimal app using dappkit 

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7174]
a simple dummy app that we can use to repro bugs (i.e. with the Valora wallet deeplink callbacks, etc.) and help debug

use alex's useful app for this, transfer alex's project to clabs

would need mobile and web dapp that is kept up to date and can serve as starting kit that can individuals can clone.

**Comment by eelanagaraj** [comment]
Progress on expo-based web-app (with dappkit-web locally available for development) https://github.com/celo-org/dappkit-web-starter. Due to running into some weird tab bugs on Chrome and Safari, it for now only includes connecting to Valora (authorizing account), but should also add tx-signing in the future.

Currently using this setup to debug some weird issues on iOS with Chrome and Safari (different issues).

As discussed in the DevX sync today, it may also make sense to have a NextJS-based test app to be able to better isolate if weird behavior is coming from React, Expo, DappKit, or wherever else.

**Comment by eelanagaraj** [comment]
Spent time looking into a NextJS dummy app in addition to the current janky expo web dummy, but it seems like a huge time sink and probably not worth continuing with that for now. (Could not get it to build/compile properly when using dappkit + react with NextJS).

Looking into some of the web refactoring of dappkit -- for now it probably makes the most sense to just add web specific functions where necessary.

**Comment by eelanagaraj** [comment]
Added a README + cleaned up the deps a bit; would appreciate if someone can try cloning/running the app on their phone as a sanity check!

https://github.com/celo-org/dappkit-web-starter/

**Comment by critesjosh** [comment]
@eelanagaraj I just tried this and the package.json references a local version of dappkit that isn't in the repo. 

https://github.com/celo-org/dappkit-web-starter/blob/957a316da651cd2caf2d2d8bfacbf7355a6e0e7c/package.json#L10

**Comment by eelanagaraj** [comment]
@critesjosh yes! (I timed this weirdly with the docs being published before but:) should now be fixed, was waiting for the new dappkit version to be published but probably should have waited on removing the copied local version of dappkit until that. Anyways, should work now, let me know if you run into issues (as this will also be good debugging/issue-finding for the dappkit-web implementation) :)
