### ISSUE TITLE
Investigate and Document how Attestation-Services can Support for China SMS

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7202]
There are extra hoops validators need to jump through to support sending SMS to China. We have a community member building a Valora-like wallet for China, which will need verification support.

Current
SMS providers (Twilio/Nexmo/MB) do not allow sending SMS to Chinese phone numbers due to regulations. As such our verifications success rate is 0% from China.

**Comment by 0xarthurxyz** [comment]
Closing this ticket because China SMS support (for decentralised AS) is deprioritised. See [comment](https://github.com/celo-org/celo-monorepo/issues/8741#issuecomment-1007403244) in this ticket: [Investigate priority of supporting China phone onboarding #8741](https://github.com/celo-org/celo-monorepo/issues/8741)
