### ISSUE TITLE
[Attestation Service] Measure and Improve SMS Carrier Success Rate

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7369]
We've observed a high correlation with attestation completion rate and mobile carrier. See the [weekly test analysis](https://docs.google.com/spreadsheets/d/1kHf4fBqQdZJG3bpEo4oQnRaTeB3LL41VFyp1_yLZ9hM/edit#gid=151590190) and this one-off [success rate by carrier analysis](https://docs.google.com/spreadsheets/d/1bfJRNc9c3nFfDI7aUzry3fth9PCObRM4nWZthd5K_mo/edit#gid=0).

Improving this can be broken down into three efforts:
1. Tracking Carrier x Country x SMS Provider success rates. Identify if there are certain SMS providers that perform better for a particular country/carrier combination. If so, we can support this prioritization in the AS.
2. 8-digit code rollout and monitoring. We should track the impact of the 8-digit code rollout across all of our dashboards.
3. Work with SMS Providers to surface issues with specific carriers.

**Comment by 0xarthurxyz** [comment]
@codyborn Closing this epic because we completed the analytics part of this ticket. 

Going forward, I'm tracking the Twilio Customer Service and other tickets in the following epic "[[Attestation Service] SMS Coverage and SMS Providers#8080](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8080)"
