### ISSUE TITLE
DappKit should return the phone number identifier for a Valora wallet

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#7428]
Certain dapps like ImpactMarket would like to check the verification status and uniqueness of a phone number for one of their users. This can help with simple fraud prevention if a user is creating multiple accounts with the same phone number or claiming to own a number that is not truly verified. Today the Dapp developer will have to process events to see the address->PN identifier relationship since the only mapping that's stored on chain is from PN Identifier->Address.

DappKit/WalletConnect should return the phone number identifier for a Valora wallet. This allows easy lookup of verification status for an account.

**Comment by aslawson** [comment]
Should be super easy to add.

**Comment by codyborn** [comment]
@nambrot queued it up🏌️‍♂️
https://github.com/celo-org/celo-monorepo/compare/nambrot/dappkit-pepper?expand=1
https://github.com/celo-org/wallet/compare/nambrot/pepper-dappkit?expand=1

**Comment by aslawson** [comment]
@nambrot is anything needed to make these pull requests? ^ were you hoping for someone else to test it?

**Comment by nambrot** [comment]
Oh I didn't just want to drive-by create PRs without consulting y'all, but IMO these should be pretty straightiforward, so happy to just create them and get them merged

**Comment by aslawson** [comment]
sounds good. looks like your impl returns the `pepper` rather than `identifier.` as part of this, can you could add a blurb under [here](https://docs.celo.org/developer-guide/dappkit/usage#requesting-account-address) about how the dappkit will:
1. return both `phoneNumber` and `pepper`
2. how to derive the identifier
3. how to confirm request mappings from onchain in a way the dev can confirm if its a singular mapping (https://docs.celo.org/developer-guide/sdk-code-reference/summary-2/modules/_wrappers_attestations_.attestationswrapper#lookupidentifiers)

**Comment by aslawson** [comment]
@nambrot ^ just wanted to make sure we also have the documentation for how devs can access this new feature

**Comment by aslawson** [comment]
Also made a separate ticket to add this functionality to WalletConnect as well
https://app.zenhub.com/workspaces/devx-backlog-board-6009f3d1a7a39b001018f159/issues/celo-org/celo-monorepo/7584

**Comment by nambrot** [comment]
Was this what you were envisioning? https://github.com/celo-org/celo-monorepo/pull/7546/commits/6160f74b7409b5af1f4e869db07fe4fc29cbec53

**Comment by aslawson** [comment]
@nambrot added a comment. otherwise looks good 👍
