### ISSUE TITLE
Verify released contracts using sourcify 

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7439]
### Expected Behavior

Celo contracts verified on https://sourcify.dev/ 

### Current Behavior

No verified contracts on sourcify (or blockscout)

https://docs.blockscout.com/for-projects/premium-features/contracts-verification-via-sourcify

**Comment by zviadm** [comment]
Just a note that might be helpful. I recently integrated fetching verified contract metadata from sourcify in Celo Terminal. It was surprisingly easy to do and also verification side was very easy and smooth too directly with https://sourcify.dev.

One really nice thing that is also possible with `sourcify` is that once you verify contracts on alfajores or baklava, you don't even need to do anything to verify them on mainnet as long as contracts match exactly, since it will do automatic bytecode matching and find appropriate metadata + source. 

For verification itself, using sourcify api directly can be easier than having to go through blockscout:  https://github.com/ethereum/sourcify/blob/master/docs/api/server/verification1/verify.md
https://github.com/ethereum/sourcify#api

**Comment by yorhodes** [comment]
@kevjue worked with this tool during ubeswap audit, could be a good candidate

**Comment by yorhodes** [comment]
blocked on https://github.com/celo-org/celo-monorepo/issues/7855

**Comment by yorhodes** [comment]
https://github.com/ethereum/sourcify/issues/468
