### ISSUE TITLE
Governance should not remove past proposals from storage

### ISSUE THREAD

**Issue by nambrot** [celo-org/celo-monorepo#7522]
### Expected Behavior

While it was done to encourage gas savings, the importance and frequency of governance proposals probably could allow us to just keep it in storage until it becomes cost-prohibitive again. It would benefit for tooling that does not want to rely on an on-chain indexer which either isn't easily doable right now or a tool like the celocli generally won't.

### Current Behavior

execution of a governance proposal removes it from storage.

**Comment by nambrot** [comment]
@yorhodes @aslawson Curious to get your thoughts

fyi @jmrossy

**Comment by jmrossy** [comment]
@nambrot Thanks for creating an issue for this.

Where to draw the line between what stays on chain and what doesn't is subjective but this to me feels like a good candidate for keeping on-chain. 

Nam mentioned the CLI, CeloWallet.app would also benefit from this, e.g. to show a Governance history screen. I had to skip that feature because this isn't doable today even with an on-chain indexer. The `ProposalQueued` events don't include a metadata url.

**Comment by aslawson** [comment]
ya i think this is one from our governance 2.0. i also see value in it -- especially for ones that at least get to the referendum phase (if we are concerned with too many being proposed in the future...)

**Comment by yorhodes** [comment]
imo executed proposals should persist, expired should be garbage collected

**Comment by aslawson** [comment]
what about non-executed proposals that were in referendum phase? so we have historical reference of voting activity for those?
