### ISSUE TITLE
Review Ubeswap Smart Contract Code/Deployment

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7665]
- Verify Ubeswap addresses have expected deployments
- Review General UniswapV2 risk 
- Review smart contracts + deployment/configuration risk

https://celo-org.slack.com/archives/C01RX722WDS/p1616086517002400

**Comment by yorhodes** [comment]
- Focus on UniswapV2 core over Synthetix staking LP contracts
  - Unaudited moola pairs not a priority

**Comment by yorhodes** [comment]
https://uniswap.org/audit.html

**Comment by macalinao** [comment]
Hi everyone,

In terms of priorities of audit:
- https://github.com/Ubeswap/ubeswap -- core contracts, you will definitely be interacting with these
- Farming -- you'll likely be staking into a StakingRewards.sol pool. I'll verify these addresses on sourcify whenever I get a chance to deploy the pools.
- Governance -- you may end up holding Ube tokens, but this is very low priority since governance has no control over your funds. We don't have any proxies or excessive admin rights.

**Comment by kevjue** [comment]
epic #7719 was created to replace this issue.
