### ISSUE TITLE
Release Gold Contract cEUR Investigations

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#7849]
Release Gold contracts should allow withdraw of cEUR (similar to cUSD) in the case that someone mistakenly sends cEUR to it. More generally, this should be established for all ERC-20 tokens but will require thoughtfulness in how this impacts Locked Celo withdrawal.

Additionally, this ticket should explore the impacts of removing the self destruct from the withdraw function as currently it can self destruct with ERC-20 tokens like cEUR or cUSD.

**Comment by nambrot** [comment]
@aslawson Is the investigation to see how important the removal is or how to implement it? I assume the latter is pretty straightforward?

**Comment by nambrot** [comment]
Moving it to low priority since we don't want to upgrade existing contracts

**Comment by aslawson** [comment]
@nambrot -- @yorhodes had mentioned that this would require thoughtfulness in design since we wouldn't want to enable withdrawals for all ERC-20 tokens which could impact Locked Celo. Also the impacts to removing the auto-self destruct means we will likely have a bunch of these contracts living forever, and what is the impact of that?

Agree, I think this is also low priority.

**Comment by nambrot** [comment]
@yorhodes can you expand on the first concern? I don't see much of a problem with enabling a generic withdraw for any token (assuming of course it doesn't self-destruct).

I'd say the proposal would be to remove the self-destruct from the withdraw and expose it via a dedicated function so that beneficiaries can still call it to reap the gas refund

**Comment by m-chrzan** [comment]
Resolved in #8750
