### ISSUE TITLE
Sourcify does not support library linking

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#7855]
### Expected Behavior

Core contract verification not limited by sourcify support

### Current Behavior

Library linking is used pervasively in the core contracts, making a full match impossible

**Comment by yorhodes** [comment]
upstream issue here https://github.com/ethereum/sourcify/issues/468

**Comment by yorhodes** [comment]
see https://celo-org.slack.com/archives/C020XU77090/p1621367320000600?thread_ts=1620386120.009000&cid=C020XU77090

**Comment by zviadm** [comment]
Is it possible to get partial matches? That still provides a lot of value, because partial match means that contract ABI is valid and verified. 

For a lot of tools (like Wallets), having verified ABI is already very useful and big improvement in UX because now transactions can be parsed and displayed with more information.

**Comment by yorhodes** [comment]
closed by https://github.com/ethereum/sourcify/pull/479
