### ISSUE TITLE
Create installable package for the disbursement tool 

### ISSUE THREAD

**Issue by jbsibille** [celo-org/celo-monorepo#7867]
What is considered done:
We want users to be able to download and install our version of celo terminal as easily as the original version (cf the dmg on celoterminal.com). 
Once they have installed it, they can use it in parallel to the "barebone" celo terminal

**Comment by carterqw2** [comment]
@jbsibille in order to be able to get this, we need to notarize our builds (more details [here](https://kilianvalkhof.com/2019/electron/notarizing-your-electron-application/)) using a [code signing certificate](https://help.apple.com/xcode/mac/current/#/dev154b28f09). It seems that we'll need a Mac developer ID/account, could you figure out if we have/can get one?
