### ISSUE TITLE
[L03] Proposal might suffer compounded loss when cancelled

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8324]
When cancelling a proposal, the cancelExchangeProposal function calls getSellTokenAndSellAmountto return the target token and token amount for the refund. In L408 of getSellTokenAndSellAmount, a mechanism is implemented to cap the returned value to the balance of GrandaMento contract in case the conversion from units to value for stable token ends up bigger than the contract balance.
However if there are multiple proposals being cancelled, the design of this mechanism will compound the potential loss to the very last proposal. Although the value is unlikely to be significant, the design seems inconsiderate.
Consider changing the design to better handle potential conversion loss. For instance, consider using an accounting system which only depends on &#8220;units&#8221; rather than &#8220;value&#8221;, thus avoiding imprecision from conversions.

**Comment by m-chrzan** [comment]
If there are any imprecisions, they are likely going to be on the order of fractions of a cUSD, whereas Granda Mento transfers are expected to be on the order of hundreds of thousands/millions cUSD.

Due to StableToken's inflation mechanism, there's no way to transact directly in units, a(n inherently imprecise) conversion to value is necessary.
