### ISSUE TITLE
Baklava cLabs validators do not have locked CELO quorum to pass governance proposals with 0.9+ agreement)

### ISSUE THREAD

**Issue by yorhodes** [celo-org/celo-monorepo#8574]
### Expected Behavior

Contract releases can be conducted on baklava via governance proposal

### Current Behavior

Proposals cannot be passed by voting from cLabs validator 0 and validator 1

**Comment by martinvol** [comment]
Fixed by adding more funds to the validator-0 in these two tx:
https://baklava-blockscout.celo-testnet.org/tx/0x67a27e53f8a9b6a919f5c1e3708f50d6f7a2542e33120ce0de3838c5344e5dad/token-transfers
https://baklava-blockscout.celo-testnet.org/tx/0x0060865b4d1ef5320f1ca6882cbcf663281afebc0c0b5c57b35eae7849ada046/token-transfers
