### ISSUE TITLE
Investigation for design of Attestation Service V2

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8589]
We may want to create a more centralized attestation service based on feedback from wallets and user needs.

- Gather requirements and advice for shaping Attestation Service v2
- Put together a design proposal for the new service

Requirements gathering + initiative doc

**Comment by eelanagaraj** [comment]
WIP requirements gathering jamboard [here](https://jamboard.google.com/d/19NBWrbb-EMZ5ArpA6EJ7Ug8JK5QngI_0PlPc0_M9uKs/viewer?f=0), assumptions not tested yet

**Comment by eelanagaraj** [comment]
TODOs:
- evaluate the effort + opportunity costs of this vs. 3rd party credentials
- Continue building support for this with data

**Comment by eelanagaraj** [comment]
@arthurgousset does it make sense to close this ticket now that you've created more specific investigation tickets? (or just deprioritize for the coming sprints)

**Comment by 0xarthurxyz** [comment]
@eelanagaraj 

### For context
This ticket belongs to an epic ("[Attestation Service v2#8588](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8588)"), which I've simply added to a higher level epic ("[[Attestation Service] Explore Trusted Issuer Model#8762](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8762)") so the info contained here is not lost. 

I was missing context on whether this ticket contains useful information, so I preferred not closing it.

But it doesn't seem relevant on your end, so I think it makes sense to close this ticket because:
- we can re-open it or created a more spec'ed out version if and when we have confirmation that a "centralised" AS pilot will be run with a partner
- we agreed to prioritise the investigation of the **root cause** of failure rates (in this epic "[[Attestation Service] Investigate failure rates (Analytics)#8778](https://app.zenhub.com/workspaces/identity-backlog-board-60e61301c3dc55000e540b61/issues/celo-org/celo-monorepo/8778)", prior to designing a solution to those problems.

**Comment by eelanagaraj** [comment]
Closing in favor of the ASv1 friction exploration tickets; we can always reopen/open new specific tickets accordingly for ASv2.
