### ISSUE TITLE
[ASv2] Data Standards Design

### ISSUE THREAD

**Issue by aslawson** [celo-org/celo-monorepo#8590]

**Comment by alecps** [comment]
- break down into smaller tickets

**Comment by eelanagaraj** [comment]
Since we have limited the scope of this, this should be completed by [this section](https://www.notion.so/clabsco/ASv2-On-chain-Registry-Protocol-47e7850656444c37973856e0634ee2f9#100f427e66a54ab3a998e9aa257983ce) in the protocol design doc. During implementation we should determine whether to use the described EIP712 data format or a proprietary bytestring for attestation claims.

I think we can close this ticket for now but maybe there are things you think are missing here @alecps @isabellewei ?
