### ISSUE TITLE
cREAL faucet support - celotool & standalone faucet

### ISSUE THREAD

**Issue by martinvol** [celo-org/celo-monorepo#8721]

**Comment by pedro-clabs** [comment]
@eelanagaraj added support for multiple stable currencies on [PR #7579](https://github.com/celo-org/celo-monorepo/pull/7579).

Contract-kit has been upgraded ([PR #9153](https://github.com/celo-org/celo-monorepo/pull/9153)) to a version that supports cREAL. We'd need to deploy the faucet back-end.

**Comment by eelanagaraj** [comment]
@pedro-clabs feel free to reach out if you need reviews/run into issues! may also be a good opportunity to:
- move the faucet low-balance alert to the issuance & oracles informational on-call rotation (currently I am the only one who receives emails i believe); also we need to add "cREAL" to the response regex so that cREAL low balances are tracked, but this is trivial
- reduce the amount fauceted on each request from 5 CELO, 10 x stabletoken to a smaller amount (since the faucet is depleted increasingly often, and the alfajores validators seem to not be replenishing funds at the same rate)
