### ISSUE TITLE
Attestation Service self-help service

### ISSUE THREAD

**Issue by codyborn** [celo-org/celo-monorepo#8856]
## Requirements

A service that allows a validator to get notified on actionable Attestation Service issues. 

A validator should be able to provide their email or discord handle and get notified when there's some action they need to take for their service. There should be a way for cLabs to update the rules over time if new alert types are needed.

## Potential solution

- Validator adds contact info to attestation config (status endpoint) or [attestation service metadata](https://docs.celo.org/celo-codebase/protocol/identity/metadata)
- Metadata crawler service monitors for errors and notifies the validator when an issue is found
  - The service today queries chain state and status endpoints
  - We should also be able to create alerts from BigQuery data (perhaps one new DBT model that aggregates all actionable error types).

**Comment by eelanagaraj** [comment]
After chatting with @lvpeschke about monitoring and observability things, this could also be a chance for us to move away from the use of the mainnet_data_crawler to ping attestation services entirely (since this is something that will possibly be deprecated in blockscout in the future). This would involve looking into how often we are querying chain state + what chain state (i.e. are validators elected or not, etc.) and to perhaps instead keep a running list of attestation services/validators (given that the churn here is pretty low) and then refactor/redo how we check that those endpoints are up.

Additionally, we can check in with the blockchain team regarding their own work on setting up alerts for individual validators.

**Comment by alecps** [comment]
De-prioritizing this in favor of ASv2
