### ISSUE TITLE
Users SBAT choose between system auth or pincode

### ISSUE THREAD

**Issue by jmrossy** [celo-org/celo-monorepo#897]
### Expected Behavior

Change enable security screen to allow users to choose

First proposal for new design:
https://www.figma.com/file/E3kgMuySj6gDboO3HdU9cixK/Wallet--3.0?node-id=1921%3A215

### Current Behavior

Defaults to system auth

**Comment by coreycelo** [comment]
Looks like I can't edit Expected Behavior above. 

Made some minor style updates:
<img width="1008" alt="Screen Shot 2019-09-16 at 5 13 37 PM" src="https://user-images.githubusercontent.com/51388535/65001814-e97d0980-d8a5-11e9-8783-41bfaf2431ac.png">

[Updated Figma link](https://www.figma.com/file/M2F3eJWIA8sI3eihpT9hxM/Security-Screen-Create-New-PIN?node-id=0%3A1)
