### ISSUE TITLE
Coordinate Valora upgrade to v1.5.3 of @celo/identity

### ISSUE THREAD

**Issue by alecps** [celo-org/celo-monorepo#9802]

**Comment by arthurgousset** [comment]
Reached out to Valora. Waiting for confirmation

**Comment by arthurgousset** [comment]
Sprint planning today: 
- Arthur - Checked in with @jeanregisser today to see progress on upgrading Valora's package dependency
- Alec - We'd like to delete some code when this is completed

**Comment by arthurgousset** [comment]
Sprint planning: 
- Would be good before we deploy to mainnet

**Comment by arthurgousset** [comment]
Sprint planning: 
- Alec - Valora is tied to the package version of Komencitkit, so that makes upgrading packages a little harder for them
- Alec - Query whether upgrading to CK 2.0 might be backwards compatible with komencikit v1
- Alec - We should update estimate to account for redeployment of Komenci
- Eela - Can we skip this part all-together. Feels like a time sink. 
- Alec - Will probably look into this.

**Comment by alecps** [comment]
Valora has stopped using Komenci. This is no longer necessary
