### ISSUE TITLE
Audit timeout logic

### ISSUE THREAD

**Issue by eelanagaraj** [celo-org/celo-monorepo#9845]
- Signer timeout logic is sketchy
  - even though the signer will now respond with a 500, it tries to also send an additional response if it does complete its logic (i.e. can timeout, send that response, and then log that it has tried to send a different success/failure response)
  - timeout errors don't roll back DB transactions (would need to move the timeouts into the db transactions for this to happen)
- Consider whether it makes sense to remove the endpoint timeout logic, and push this handling to the requester (since the combiner already also implements its own signer timeout logic) as well as the `perform` functions themselves where trxs can be rolled back
- Audit the combiner timeouts & its handling of signer timeout logic

Output could be: 
- removing timeout logic and explanation of why

**Comment by arthurgousset** [comment]
Sprint planning: 
- Eela - this one is kind of tricky, realised some timeout logic is funky while checking db logic
- Eela - one part of this is fixed, we should decide whether we want the timeout logic in the signer, because it exists in the combiner too
- Alec - We can always timebox tickets
- Alec - Can we do this after the merge? 
- Eela - Should investigate before merge
- Consensus around 5 dev days
- Could timebox at 3 days for investigation

**Comment by arthurgousset** [comment]
Sprint planning: 
- Pretty close to submitting PR (tonight)
